
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

#ifndef MetaMetadata_MetaFundamental_Partial_h
#define MetaMetadata_MetaFundamental_Partial_h

#include "..\Core.h"

// forward declarations from other files


// dependencies


// forward declarations

namespace reflection { 
}

namespace reflection { 

	// classes
	
} /* namespace reflection */ 

#endif // MetaMetadata_MetaFundamental_Partial_h
