
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

#ifndef MetaMetadata_MetaProject_Partial_h
#define MetaMetadata_MetaProject_Partial_h

#include "..\Core.h"

// forward declarations from other files


// dependencies

#include "MetaFundamental.h"
#include "MetaClasses.h"

// forward declarations

namespace reflection { 
	class MetadataFile; class MetadataFile_Partial;
	class MetadataFilesCollection; class MetadataFilesCollection_Partial;
	class MetadataFolder; class MetadataFolder_Partial;
	class MetadataFoldersCollection; class MetadataFoldersCollection_Partial;
	class MetadataMemberGroup; class MetadataMemberGroup_Partial;
	class MemberGroupsCollection; class MemberGroupsCollection_Partial;
	class MetadataProject; class MetadataProject_Partial;
}

namespace reflection { 

	// classes
	
	namespace MetadataFile_ByteStream
	{
		bool ObjectFromByteStream( core::ByteStreamReader & stream, reflection::MetadataFile & dataObject );
	};

	class MetadataFile_Partial
	{
	public:
		MetadataFile_Partial();
		~MetadataFile_Partial();

		string Get_Name() const;
		void Set_Name( string value );
		
		reflection::MetadataFolder * Get_Parent() const;
		void Set_Parent( reflection::MetadataFolder * value );
		
		string Get_Namespace() const;
		void Set_Namespace( string value );
		
		reflection::MetadataFileContent * Get_Content() const;
		void Set_Content( reflection::MetadataFileContent * value );
		
		bool Get_GenerateGui() const;
		void Set_GenerateGui( bool value );
		
		bool Get_GenerateSerialization() const;
		void Set_GenerateSerialization( bool value );
		
	private:
		string Name;
		reflection::MetadataFolder * Parent;
		string Namespace;
		reflection::MetadataFileContent * Content;
		bool GenerateGui;
		bool GenerateSerialization;
	};

	namespace MetadataFilesCollection_ByteStream
	{
		bool ObjectFromByteStream( core::ByteStreamReader & stream, reflection::MetadataFilesCollection & dataObject );
	};

	class MetadataFilesCollection_Partial : public core::CollectionOf < reflection::MetadataFile * >
	{
	public:
		MetadataFilesCollection_Partial();
		~MetadataFilesCollection_Partial();
	};

	namespace MetadataFoldersCollection_ByteStream
	{
		bool ObjectFromByteStream( core::ByteStreamReader & stream, reflection::MetadataFoldersCollection & dataObject );
	};

	class MetadataFoldersCollection_Partial : public core::CollectionOf < reflection::MetadataFolder * >
	{
	public:
		MetadataFoldersCollection_Partial();
		~MetadataFoldersCollection_Partial();
	};

	namespace MetadataFolder_ByteStream
	{
		bool ObjectFromByteStream( core::ByteStreamReader & stream, reflection::MetadataFolder & dataObject );
	};

	class MetadataFolder_Partial
	{
	public:
		MetadataFolder_Partial();
		~MetadataFolder_Partial();

		string Get_Name() const;
		void Set_Name( string value );
		
		reflection::MetadataFolder * Get_Parent() const;
		void Set_Parent( reflection::MetadataFolder * value );
		
		reflection::MetadataProject * Get_ParentProject() const;
		void Set_ParentProject( reflection::MetadataProject * value );
		
		string Get_Namespace() const;
		void Set_Namespace( string value );
		
		reflection::MetadataFoldersCollection_Partial & Get_Folders();
		reflection::MetadataFoldersCollection_Partial const & Get_Folders() const;
		
		reflection::MetadataFilesCollection_Partial & Get_Files();
		reflection::MetadataFilesCollection_Partial const & Get_Files() const;
		
	private:
		string Name;
		reflection::MetadataFolder * Parent;
		reflection::MetadataProject * ParentProject;
		string Namespace;
		reflection::MetadataFoldersCollection_Partial Folders;
		reflection::MetadataFilesCollection_Partial Files;
	};

	namespace MetadataMemberGroup_ByteStream
	{
		bool ObjectFromByteStream( core::ByteStreamReader & stream, reflection::MetadataMemberGroup & dataObject );
	};

	class MetadataMemberGroup_Partial
	{
	public:
		MetadataMemberGroup_Partial();
		~MetadataMemberGroup_Partial();

		string Get_Name() const;
		void Set_Name( string value );
		
		string Get_PartialFileExtension() const;
		void Set_PartialFileExtension( string value );
		
	private:
		string Name;
		string PartialFileExtension;
	};

	namespace MemberGroupsCollection_ByteStream
	{
		bool ObjectFromByteStream( core::ByteStreamReader & stream, reflection::MemberGroupsCollection & dataObject );
	};

	class MemberGroupsCollection_Partial : public core::CollectionOf < reflection::MetadataMemberGroup * >
	{
	public:
		MemberGroupsCollection_Partial();
		~MemberGroupsCollection_Partial();
	};

	namespace MetadataProject_ByteStream
	{
		bool ObjectFromByteStream( core::ByteStreamReader & stream, reflection::MetadataProject & dataObject );
	};

	class MetadataProject_Partial
	{
	public:
		MetadataProject_Partial();
		~MetadataProject_Partial();

		string Get_CoreNamespace() const;
		void Set_CoreNamespace( string value );
		
		reflection::MetadataFolder const & Get_Metadata() const;
		void Set_Metadata( reflection::MetadataFolder const & value );
		
		reflection::MemberGroupsCollection_Partial & Get_MemberGroups();
		reflection::MemberGroupsCollection_Partial const & Get_MemberGroups() const;
		
	private:
		string CoreNamespace;
		reflection::MetadataFolder * Metadata;
		reflection::MemberGroupsCollection_Partial MemberGroups;
	};

} /* namespace reflection */ 

#endif // MetaMetadata_MetaProject_Partial_h
