
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

#include "ProjectLevels.h"

#include "..\..\Reflection.h"

#include "ProjectLevels.Reflection.h"

// depends on parent/reference files
#include "Project.h"
// depends on reflection files
#include "..\Engine\Fundamental.Reflection.h"

namespace level { 

class Levels_Member_name : public reflection::ValueName
{
public:
	Levels_Member_name()
	{
		Set_Guid("2fccc80d-24cd-4f58-9f2c-19a1dee87f9b");
		Set_Name("name");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		level::Levels * pThis = core::polymorphic_downcast< level::Levels * >( &ThisUnityped );
		if ( !pThis )
			return false;
		string_Boxed const * pDataObject = core::polymorphic_downcast < string_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->Set_name( pDataObject->value );
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		level::Levels const * pThis = core::polymorphic_downcast< level::Levels const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		string_Boxed * pDataObject = CORE_NEW string_Boxed();
		pDataObject->value = pThis->Get_name();
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		level::Levels * pThis = core::polymorphic_downcast< level::Levels * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::uint32 size; if ( !stream.ReadSize( size ) ) return false;
		void const * bytes; if ( !stream.ReadBytes( size, bytes ) ) return false;
		string value( (char*)bytes, size );
		pThis->Set_name( value );
		return true;
	}	
};

class Levels_Member_folders : public reflection::Collection
{
public:
	Levels_Member_folders()
	{
		Set_Guid("6d4f2370-78c6-4101-9cc7-0f28e4a18045");
		Set_Name("folders");
	}
	virtual bool GetCollectionObject( core::DataObject const & ThisUnityped, core::ICollection const * & pCollectionUnityped ) const
	{
		level::Levels const * pThis = core::polymorphic_downcast< level::Levels const * >( &ThisUnityped );
		if ( !pThis )
			return false;		
		pCollectionUnityped = &pThis->Get_folders();
		return true;
	}
	virtual bool GetCollectionObject( core::DataObject & ThisUnityped, core::ICollection * & pCollectionUnityped ) const
	{
		level::Levels * pThis = core::polymorphic_downcast< level::Levels * >( &ThisUnityped );
		if ( !pThis )
			return false;		
		pCollectionUnityped = &pThis->Get_folders();
		return true;
	}
};

class Levels_Member_parent : public reflection::ParentReference
{
public:
	Levels_Member_parent()
	{
		Set_Guid("26cd9e14-4865-41b4-b074-a63cb275af8d");
		Set_Name("parent");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		level::Levels * pThis = core::polymorphic_downcast< level::Levels * >( &ThisUnityped );
		if ( !pThis )
			return false;
			
		game::Game * pDataObject = NULL;			
		if ( pDataObjectUnityped )
		{
			pDataObject = core::polymorphic_downcast< game::Game * >( pDataObjectUnityped );
			if ( !pDataObject )
				return false;
		}		
		pThis->Set_parent( pDataObject );
		return true;	
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		level::Levels const * pThis = core::polymorphic_downcast< level::Levels const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		pDataObjectUnityped = pThis->Get_parent();
		return true;	
	}
};


Levels_Reflection::Levels_Reflection()
{
	Set_Guid("daaf8113-6b58-48a3-a19e-94b9e6da3a74");
	Set_TypeName("Levels");	
	Get_Members().Add( CORE_NEW Levels_Member_name() );
	Get_Members().Add( CORE_NEW Levels_Member_folders() );
	Get_Members().Add( CORE_NEW Levels_Member_parent() );
}

void Levels_Reflection::CopyObjectDataFromTo( Levels const & from, Levels & to )
{
	// TODO: implement
}


class LevelFolder_Member_name : public reflection::ValueName
{
public:
	LevelFolder_Member_name()
	{
		Set_Guid("52f0b117-c9c7-4825-967e-f12bcd128c45");
		Set_Name("name");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		level::LevelFolder * pThis = core::polymorphic_downcast< level::LevelFolder * >( &ThisUnityped );
		if ( !pThis )
			return false;
		string_Boxed const * pDataObject = core::polymorphic_downcast < string_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->Set_name( pDataObject->value );
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		level::LevelFolder const * pThis = core::polymorphic_downcast< level::LevelFolder const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		string_Boxed * pDataObject = CORE_NEW string_Boxed();
		pDataObject->value = pThis->Get_name();
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		level::LevelFolder * pThis = core::polymorphic_downcast< level::LevelFolder * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::uint32 size; if ( !stream.ReadSize( size ) ) return false;
		void const * bytes; if ( !stream.ReadBytes( size, bytes ) ) return false;
		string value( (char*)bytes, size );
		pThis->Set_name( value );
		return true;
	}	
};

class LevelFolder_Member_parent : public reflection::ParentReference
{
public:
	LevelFolder_Member_parent()
	{
		Set_Guid("58361e6e-810c-4720-93fa-1ecc7307ea91");
		Set_Name("parent");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		level::LevelFolder * pThis = core::polymorphic_downcast< level::LevelFolder * >( &ThisUnityped );
		if ( !pThis )
			return false;
			
		level::Levels * pDataObject = NULL;			
		if ( pDataObjectUnityped )
		{
			pDataObject = core::polymorphic_downcast< level::Levels * >( pDataObjectUnityped );
			if ( !pDataObject )
				return false;
		}		
		pThis->Set_parent( pDataObject );
		return true;	
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		level::LevelFolder const * pThis = core::polymorphic_downcast< level::LevelFolder const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		pDataObjectUnityped = pThis->Get_parent();
		return true;	
	}
};

class LevelFolder_Member_dependencies : public reflection::Collection
{
public:
	LevelFolder_Member_dependencies()
	{
		Set_Guid("2a19daa4-3fe7-4b9a-acca-22a584477e7f");
		Set_Name("dependencies");
	}
	virtual bool GetCollectionObject( core::DataObject const & ThisUnityped, core::ICollection const * & pCollectionUnityped ) const
	{
		level::LevelFolder const * pThis = core::polymorphic_downcast< level::LevelFolder const * >( &ThisUnityped );
		if ( !pThis )
			return false;		
		pCollectionUnityped = &pThis->Get_dependencies();
		return true;
	}
	virtual bool GetCollectionObject( core::DataObject & ThisUnityped, core::ICollection * & pCollectionUnityped ) const
	{
		level::LevelFolder * pThis = core::polymorphic_downcast< level::LevelFolder * >( &ThisUnityped );
		if ( !pThis )
			return false;		
		pCollectionUnityped = &pThis->Get_dependencies();
		return true;
	}
};

class LevelFolder_Member_blocks : public reflection::Collection
{
public:
	LevelFolder_Member_blocks()
	{
		Set_Guid("b83ac6fc-4ebe-4bcf-8ede-c3ce3e2f67a4");
		Set_Name("blocks");
	}
	virtual bool GetCollectionObject( core::DataObject const & ThisUnityped, core::ICollection const * & pCollectionUnityped ) const
	{
		level::LevelFolder const * pThis = core::polymorphic_downcast< level::LevelFolder const * >( &ThisUnityped );
		if ( !pThis )
			return false;		
		pCollectionUnityped = &pThis->Get_blocks();
		return true;
	}
	virtual bool GetCollectionObject( core::DataObject & ThisUnityped, core::ICollection * & pCollectionUnityped ) const
	{
		level::LevelFolder * pThis = core::polymorphic_downcast< level::LevelFolder * >( &ThisUnityped );
		if ( !pThis )
			return false;		
		pCollectionUnityped = &pThis->Get_blocks();
		return true;
	}
};


LevelFolder_Reflection::LevelFolder_Reflection()
{
	Set_Guid("65461cf1-2c85-4ab0-9ed8-7a951902236f");
	Set_TypeName("LevelFolder");	
	Get_Members().Add( CORE_NEW LevelFolder_Member_name() );
	Get_Members().Add( CORE_NEW LevelFolder_Member_parent() );
	Get_Members().Add( CORE_NEW LevelFolder_Member_dependencies() );
	Get_Members().Add( CORE_NEW LevelFolder_Member_blocks() );
}

void LevelFolder_Reflection::CopyObjectDataFromTo( LevelFolder const & from, LevelFolder & to )
{
	// TODO: implement
}

core::ReferenceObject * LevelFolder_Reflection::New() const
{ 
	return CORE_NEW level::LevelFolder(); 
}

void LevelFolder_Reflection::Delete( core::ReferenceObject * pDataObject ) const
{ 
	CORE_DELETE pDataObject; 
}


LevelFoldersCollection_Reflection::LevelFoldersCollection_Reflection()
{
	Set_Guid("e7cb809a-fa8f-4b52-9680-b18d03cb1a5e");
	Set_TypeName("LevelFoldersCollection");	
}

void LevelFoldersCollection_Reflection::CopyObjectDataFromTo( LevelFoldersCollection const & from, LevelFoldersCollection & to )
{
	// TODO: implement
}


class LevelBlock_Member_name : public reflection::ValueName
{
public:
	LevelBlock_Member_name()
	{
		Set_Guid("8b004694-164b-4678-b912-2ca3b24fe8b7");
		Set_Name("name");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		level::LevelBlock * pThis = core::polymorphic_downcast< level::LevelBlock * >( &ThisUnityped );
		if ( !pThis )
			return false;
		string_Boxed const * pDataObject = core::polymorphic_downcast < string_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->Set_name( pDataObject->value );
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		level::LevelBlock const * pThis = core::polymorphic_downcast< level::LevelBlock const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		string_Boxed * pDataObject = CORE_NEW string_Boxed();
		pDataObject->value = pThis->Get_name();
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		level::LevelBlock * pThis = core::polymorphic_downcast< level::LevelBlock * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::uint32 size; if ( !stream.ReadSize( size ) ) return false;
		void const * bytes; if ( !stream.ReadBytes( size, bytes ) ) return false;
		string value( (char*)bytes, size );
		pThis->Set_name( value );
		return true;
	}	
};

class LevelBlock_Member_parent : public reflection::ParentReference
{
public:
	LevelBlock_Member_parent()
	{
		Set_Guid("8c862cca-79fa-436d-a320-66ee7e3bc936");
		Set_Name("parent");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		level::LevelBlock * pThis = core::polymorphic_downcast< level::LevelBlock * >( &ThisUnityped );
		if ( !pThis )
			return false;
			
		level::LevelFolder * pDataObject = NULL;			
		if ( pDataObjectUnityped )
		{
			pDataObject = core::polymorphic_downcast< level::LevelFolder * >( pDataObjectUnityped );
			if ( !pDataObject )
				return false;
		}		
		pThis->Set_parent( pDataObject );
		return true;	
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		level::LevelBlock const * pThis = core::polymorphic_downcast< level::LevelBlock const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		pDataObjectUnityped = pThis->Get_parent();
		return true;	
	}
};

class LevelBlock_Member_files : public reflection::Collection
{
public:
	LevelBlock_Member_files()
	{
		Set_Guid("084f1b7f-89f2-4f03-8dff-14fec74b1fc9");
		Set_Name("files");
	}
	virtual bool GetCollectionObject( core::DataObject const & ThisUnityped, core::ICollection const * & pCollectionUnityped ) const
	{
		level::LevelBlock const * pThis = core::polymorphic_downcast< level::LevelBlock const * >( &ThisUnityped );
		if ( !pThis )
			return false;		
		pCollectionUnityped = &pThis->Get_files();
		return true;
	}
	virtual bool GetCollectionObject( core::DataObject & ThisUnityped, core::ICollection * & pCollectionUnityped ) const
	{
		level::LevelBlock * pThis = core::polymorphic_downcast< level::LevelBlock * >( &ThisUnityped );
		if ( !pThis )
			return false;		
		pCollectionUnityped = &pThis->Get_files();
		return true;
	}
};


LevelBlock_Reflection::LevelBlock_Reflection()
{
	Set_Guid("77924162-cb05-4f79-969e-6854a43ae1c8");
	Set_TypeName("LevelBlock");	
	Get_Members().Add( CORE_NEW LevelBlock_Member_name() );
	Get_Members().Add( CORE_NEW LevelBlock_Member_parent() );
	Get_Members().Add( CORE_NEW LevelBlock_Member_files() );
}

void LevelBlock_Reflection::CopyObjectDataFromTo( LevelBlock const & from, LevelBlock & to )
{
	// TODO: implement
}



LevelBlocksCollection_Reflection::LevelBlocksCollection_Reflection()
{
	Set_Guid("4c2def93-2fcb-4c8f-851c-88aa2c98cfd4");
	Set_TypeName("LevelBlocksCollection");	
}

void LevelBlocksCollection_Reflection::CopyObjectDataFromTo( LevelBlocksCollection const & from, LevelBlocksCollection & to )
{
	// TODO: implement
}


class LevelFile_Member_parent : public reflection::ParentReference
{
public:
	LevelFile_Member_parent()
	{
		Set_Guid("33d91469-0caa-4708-a19c-d647c0b41ff0");
		Set_Name("parent");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		level::LevelFile * pThis = core::polymorphic_downcast< level::LevelFile * >( &ThisUnityped );
		if ( !pThis )
			return false;
			
		level::LevelBlock * pDataObject = NULL;			
		if ( pDataObjectUnityped )
		{
			pDataObject = core::polymorphic_downcast< level::LevelBlock * >( pDataObjectUnityped );
			if ( !pDataObject )
				return false;
		}		
		pThis->Set_parent( pDataObject );
		return true;	
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		level::LevelFile const * pThis = core::polymorphic_downcast< level::LevelFile const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		pDataObjectUnityped = pThis->Get_parent();
		return true;	
	}
};

class LevelFile_Member_scene : public reflection::FileStorage
{
public:
	LevelFile_Member_scene()
	{
		Set_Guid("e502c1ab-993e-4d66-9366-a4eca621be55");
		Set_Name("scene");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		level::LevelFile * pThis = core::polymorphic_downcast< level::LevelFile * >( &ThisUnityped );
		if ( !pThis )
			return false;
			
		scene::Scene * pDataObject = NULL;			
		if ( pDataObjectUnityped )
		{
			pDataObject = core::polymorphic_downcast< scene::Scene * >( pDataObjectUnityped );
			if ( !pDataObject )
				return false;
		}		
		pThis->Set_scene( pDataObject );
		return true;	
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		level::LevelFile const * pThis = core::polymorphic_downcast< level::LevelFile const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		pDataObjectUnityped = pThis->Get_scene();
		return true;	
	}
};

class LevelFile_Member_name : public reflection::ValueName
{
public:
	LevelFile_Member_name()
	{
		Set_Guid("784e344b-a1c4-4ce8-8faf-f40e1c3562a2");
		Set_Name("name");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		level::LevelFile * pThis = core::polymorphic_downcast< level::LevelFile * >( &ThisUnityped );
		if ( !pThis )
			return false;
		string_Boxed const * pDataObject = core::polymorphic_downcast < string_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->Set_name( pDataObject->value );
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		level::LevelFile const * pThis = core::polymorphic_downcast< level::LevelFile const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		string_Boxed * pDataObject = CORE_NEW string_Boxed();
		pDataObject->value = pThis->Get_name();
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		level::LevelFile * pThis = core::polymorphic_downcast< level::LevelFile * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::uint32 size; if ( !stream.ReadSize( size ) ) return false;
		void const * bytes; if ( !stream.ReadBytes( size, bytes ) ) return false;
		string value( (char*)bytes, size );
		pThis->Set_name( value );
		return true;
	}	
};


LevelFile_Reflection::LevelFile_Reflection()
{
	Set_Guid("5a4f1500-59c4-430c-89ac-fa1fdfa88e46");
	Set_TypeName("LevelFile");	
	Get_Members().Add( CORE_NEW LevelFile_Member_parent() );
	Get_Members().Add( CORE_NEW LevelFile_Member_scene() );
	Get_Members().Add( CORE_NEW LevelFile_Member_name() );
}

void LevelFile_Reflection::CopyObjectDataFromTo( LevelFile const & from, LevelFile & to )
{
	// TODO: implement
}



LevelFilesCollection_Reflection::LevelFilesCollection_Reflection()
{
	Set_Guid("17a293e5-b01a-4095-b5f7-17d74a0c9b8b");
	Set_TypeName("LevelFilesCollection");	
}

void LevelFilesCollection_Reflection::CopyObjectDataFromTo( LevelFilesCollection const & from, LevelFilesCollection & to )
{
	// TODO: implement
}


class Dependency_Member_LevelFolder : public reflection::Reference
{
public:
	Dependency_Member_LevelFolder()
	{
		Set_Guid("cd7d237b-6fe5-4deb-8da2-415994aeec66");
		Set_Name("LevelFolder");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		level::Dependency * pThis = core::polymorphic_downcast< level::Dependency * >( &ThisUnityped );
		if ( !pThis )
			return false;
			
		level::LevelFolder * pDataObject = NULL;			
		if ( pDataObjectUnityped )
		{
			pDataObject = core::polymorphic_downcast< level::LevelFolder * >( pDataObjectUnityped );
			if ( !pDataObject )
				return false;
		}		
		pThis->Set_LevelFolder( pDataObject );
		return true;	
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		level::Dependency const * pThis = core::polymorphic_downcast< level::Dependency const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		pDataObjectUnityped = pThis->Get_LevelFolder();
		return true;	
	}
};


Dependency_Reflection::Dependency_Reflection()
{
	Set_Guid("2956cd4f-619d-4fc7-bfc4-84722fd742d5");
	Set_TypeName("Dependency");	
	Get_Members().Add( CORE_NEW Dependency_Member_LevelFolder() );
}

void Dependency_Reflection::CopyObjectDataFromTo( Dependency const & from, Dependency & to )
{
	// TODO: implement
}

core::ReferenceObject * Dependency_Reflection::New() const
{ 
	return CORE_NEW level::Dependency(); 
}

void Dependency_Reflection::Delete( core::ReferenceObject * pDataObject ) const
{ 
	CORE_DELETE pDataObject; 
}


Dependencies_Reflection::Dependencies_Reflection()
{
	Set_Guid("c5c17415-7309-489b-ae23-61f4ef69c532");
	Set_TypeName("Dependencies");	
}

void Dependencies_Reflection::CopyObjectDataFromTo( Dependencies const & from, Dependencies & to )
{
	// TODO: implement
}


} /* namespace level */ 
