#ifndef Metadata_Game_ProjectGlobals_Reflection_h
#define Metadata_Game_ProjectGlobals_Reflection_h

// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

namespace game { 

	// forward declarations
	class Globals;
	
	// reflection classes
	
	class Globals_Reflection : public reflection::FolderClass
	{
	public:
		Globals_Reflection();
		
		void CopyObjectDataFromTo( Globals const & from, Globals & to );
		
		virtual core::ReferenceObject * New() const;
		virtual void Delete( core::ReferenceObject * pDataObject ) const;
	};

} /* namespace game */ 

#endif // Metadata_Game_ProjectGlobals_Reflection_h
