
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

#include "ProjectGlobals.h"

namespace game { 

bool Globals_ByteStream::ObjectFromByteStream( core::ByteStreamReader & stream, game::Globals & dataObject )
{
	core::uint32 name_Size; if ( !stream.ReadSize( name_Size ) ) return false;
	void const * name_Bytes; if ( !stream.ReadBytes( name_Size, name_Bytes ) ) return false;
	string name ( (char*)name_Bytes, name_Size );
	dataObject.Set_name ( name );
	
	return true;
}


Globals_Partial::Globals_Partial()
	: name("Globals")
	, parent()
{
}

Globals_Partial::~Globals_Partial()
{
	parent = NULL;
}

string Globals_Partial::Get_name() const 
{ 
	return name; 
}
void Globals_Partial::Set_name( string value ) 
{ 
	name = value; 
}

game::Game * Globals_Partial::Get_parent() const 
{ 
	return parent; 
}
void Globals_Partial::Set_parent( game::Game * value ) 
{ 
	parent = value; 
}


} /* namespace game */ 
