
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

#ifndef Metadata_Game_Project_Partial_h
#define Metadata_Game_Project_Partial_h

#include "..\..\Core.h"

// forward declarations from other files


// dependencies

#include "ProjectGlobals.h"
#include "ProjectGui.h"
#include "ProjectLevels.h"

// forward declarations

namespace game { 
	class Game; class Game_Partial;
}

namespace game { 

	// classes
	
	namespace Game_ByteStream
	{
		bool ObjectFromByteStream( core::ByteStreamReader & stream, game::Game & dataObject );
	};

	class Game_Partial
	{
	public:
		Game_Partial();
		~Game_Partial();

		game::Globals const & Get_globals() const;
		void Set_globals( game::Globals const & value );
		
		gui::Gui const & Get_gui() const;
		void Set_gui( gui::Gui const & value );
		
		level::Levels const & Get_levels() const;
		void Set_levels( level::Levels const & value );
		
	private:
		game::Globals * globals;
		gui::Gui * gui;
		level::Levels * levels;
	};

} /* namespace game */ 

#endif // Metadata_Game_Project_Partial_h
