
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace game { 

	public partial class Game : core.ReferenceObject
	{
		public game.Globals globals = new game.Globals ();
		public gui.Gui gui = new gui.Gui ();
		public level.Levels levels = new level.Levels ();
		public string ProjectPath;
		public string ProjectName;
	}

} /* namespace game */ 
