
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.IO;
using System.Xml.Serialization;
using System.ComponentModel;

namespace metadata { 

	[XmlType("Fundamental")]
	public abstract class Fundamental_Serialization : metadata.Type_Serialization
	{
		[XmlIgnore]
		metadata.Fundamental This;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			stringToObject.Add( GuidStr.ToOptGuid(), This );	
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.Fundamental)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.Fundamental dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.Fundamental dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.Fundamental)dataObject );
		}
		protected void ToSerialization_Base( metadata.Fundamental dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
		}
		
	}

	[XmlType("FundamentalBool")]
	public class FundamentalBool_Serialization : metadata.Fundamental_Serialization
	{
		[XmlIgnore]
		metadata.FundamentalBool This;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			stringToObject.Add( GuidStr.ToOptGuid(), This );	
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.FundamentalBool)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.FundamentalBool dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.FundamentalBool dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.FundamentalBool)dataObject );
		}
		protected void ToSerialization_Base( metadata.FundamentalBool dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
		}
		
	}

	[XmlType("FundamentalString")]
	public class FundamentalString_Serialization : metadata.Fundamental_Serialization
	{
		[XmlIgnore]
		metadata.FundamentalString This;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			stringToObject.Add( GuidStr.ToOptGuid(), This );	
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.FundamentalString)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.FundamentalString dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.FundamentalString dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.FundamentalString)dataObject );
		}
		protected void ToSerialization_Base( metadata.FundamentalString dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
		}
		
	}

	[XmlType("FundamentalInt")]
	public class FundamentalInt_Serialization : metadata.Fundamental_Serialization
	{
		[XmlIgnore]
		metadata.FundamentalInt This;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			stringToObject.Add( GuidStr.ToOptGuid(), This );	
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.FundamentalInt)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.FundamentalInt dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.FundamentalInt dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.FundamentalInt)dataObject );
		}
		protected void ToSerialization_Base( metadata.FundamentalInt dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
		}
		
	}

	[XmlType("FundamentalFloat")]
	public class FundamentalFloat_Serialization : metadata.Fundamental_Serialization
	{
		[XmlIgnore]
		metadata.FundamentalFloat This;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			stringToObject.Add( GuidStr.ToOptGuid(), This );	
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.FundamentalFloat)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.FundamentalFloat dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.FundamentalFloat dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.FundamentalFloat)dataObject );
		}
		protected void ToSerialization_Base( metadata.FundamentalFloat dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
		}
		
	}

	[XmlType("FundamentalByte")]
	public class FundamentalByte_Serialization : metadata.Fundamental_Serialization
	{
		[XmlIgnore]
		metadata.FundamentalByte This;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			stringToObject.Add( GuidStr.ToOptGuid(), This );	
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.FundamentalByte)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.FundamentalByte dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.FundamentalByte dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.FundamentalByte)dataObject );
		}
		protected void ToSerialization_Base( metadata.FundamentalByte dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
		}
		
	}

	[XmlType("Enumeration")]
	public class Enumeration_Serialization : metadata.Type_Serialization
	{
		[XmlIgnore]
		metadata.Enumeration This;

		[XmlArray]
		[XmlArrayItem(typeof(metadata.Enumerator_Serialization),ElementName = "Enumerator")]
		public metadata.EnumeratorsCollection_Serialization Enumerators = new metadata.EnumeratorsCollection_Serialization();

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			stringToObject.Add( GuidStr.ToOptGuid(), This );	
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.Enumeration)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.Enumeration dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
			Enumerators.FromSerializationConstruct( This.Enumerators );
			foreach( metadata.Enumerator collectionElement in This.Enumerators )
			{
			}
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.Enumeration dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
			Enumerators.FromSerialization( stringToObject );
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.Enumeration)dataObject );
		}
		protected void ToSerialization_Base( metadata.Enumeration dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
			Enumerators.ToSerialization( This.Enumerators );
			foreach ( metadata.Enumerator_Serialization collectionElement in Enumerators )
			{
			}
		}
		
	}

	[XmlType("Enumerator")]
	public class Enumerator_Serialization : core.SerializationObject
	{
		[XmlIgnore]
		metadata.Enumerator This;

		[XmlAttribute]
		public string Name;

		[XmlAttribute]
		public int IntegralValue;

		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.Enumerator)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.Enumerator dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.Enumerator dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
			This.Name = Name;
			This.IntegralValue = IntegralValue;
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.Enumerator)dataObject );
		}
		protected void ToSerialization_Base( metadata.Enumerator dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
			Name = This.Name;
			IntegralValue = This.IntegralValue;
		}
		
	}

	[XmlType("EnumeratorsCollection")]
	public class EnumeratorsCollection_Serialization : core.SerializationCollectionOf <metadata.Enumerator_Serialization>
	{
		[XmlIgnore]
		metadata.EnumeratorsCollection This;

		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.EnumeratorsCollection)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.EnumeratorsCollection dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
			This.Clear();
			foreach( metadata.Enumerator_Serialization collectionElement in Values )
			{
				metadata.Enumerator dataCollectionElement = metadata.Serialization.ConstructData<metadata.Enumerator>( collectionElement.GetType() );
				collectionElement.FromSerializationConstruct( dataCollectionElement );
				This.Add( dataCollectionElement );
			}
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.EnumeratorsCollection dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
			foreach( metadata.Enumerator_Serialization collectionElement in Values )
				collectionElement.FromSerialization( stringToObject );
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.EnumeratorsCollection)dataObject );
		}
		protected void ToSerialization_Base( metadata.EnumeratorsCollection dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
			Clear();
			foreach( metadata.Enumerator dataCollectionElement in This )
			{
				metadata.Enumerator_Serialization collectionElement = metadata.Serialization.ConstructSerialization<metadata.Enumerator_Serialization>( dataCollectionElement.GetType() );
				collectionElement.ToSerialization( dataCollectionElement );	
				Add( collectionElement );
			}
		}
		
	}

} /* namespace metadata */ 
