
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace metadata { 

	public abstract partial class Fundamental : metadata.Type
	{
	}

	public partial class FundamentalBool : metadata.Fundamental
	{
	}

	public partial class FundamentalString : metadata.Fundamental
	{
	}

	public partial class FundamentalInt : metadata.Fundamental
	{
	}

	public partial class FundamentalFloat : metadata.Fundamental
	{
	}

	public partial class FundamentalByte : metadata.Fundamental
	{
	}

	public partial class Enumeration : metadata.Type
	{
		public metadata.EnumeratorsCollection Enumerators = new metadata.EnumeratorsCollection();
	}

	public partial class Enumerator : core.DataObject
	{
		public string Name;
		public int IntegralValue;
	}

	public partial class EnumeratorsCollection : core.CollectionOf <metadata.Enumerator>
	{
	}

} /* namespace metadata */ 
