
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.IO;
using System.Xml.Serialization;
using System.ComponentModel;

namespace metadata { 

	[XmlType("Function")]
	public abstract class Function_Serialization : metadata.Member_Serialization
	{
		[XmlIgnore]
		metadata.Function This;

		public metadata.Argument_Serialization Result;

		[XmlArray]
		[XmlArrayItem(typeof(metadata.ArgumentValue_Serialization),ElementName = "ArgumentValue")]
		[XmlArrayItem(typeof(metadata.ArgumentReference_Serialization),ElementName = "ArgumentReference")]
		public metadata.ArgumentsCollection_Serialization Arguments = new metadata.ArgumentsCollection_Serialization();

		[XmlAttribute]
		[DefaultValue(metadata.RemoteType.None)]
		public metadata.RemoteType Remote = metadata.RemoteType.None;

		[XmlAttribute]
		[DefaultValue(false)]
		public bool IsStatic = false;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			stringToObject.Add( GuidStr.ToOptGuid(), This );	
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.Function)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.Function dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
			if ( Result != null )
			{
				This.Result = metadata.Serialization.ConstructData<metadata.Argument>( Result.GetType() );
				Result.FromSerializationConstruct( This.Result );
			}
			Arguments.FromSerializationConstruct( This.Arguments );
			foreach( metadata.Argument collectionElement in This.Arguments )
			{
			}
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.Function dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
			if ( Result != null )
				Result.FromSerialization( stringToObject );
			Arguments.FromSerialization( stringToObject );
			This.Remote = Remote;
			This.IsStatic = IsStatic;
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.Function)dataObject );
		}
		protected void ToSerialization_Base( metadata.Function dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
			if ( This.Result != null )
			{
				Result = metadata.Serialization.ConstructSerialization<metadata.Argument_Serialization>( This.Result.GetType() );
				Result.ToSerialization( This.Result );
			}
			Arguments.ToSerialization( This.Arguments );
			foreach ( metadata.Argument_Serialization collectionElement in Arguments )
			{
			}
			Remote = This.Remote;
			IsStatic = This.IsStatic;
		}
		
	}

	[XmlType("FunctionUser")]
	public class FunctionUser_Serialization : metadata.Function_Serialization
	{
		[XmlIgnore]
		metadata.FunctionUser This;

		[XmlAttribute]
		public bool ExposeToLua = false;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			stringToObject.Add( GuidStr.ToOptGuid(), This );	
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.FunctionUser)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.FunctionUser dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.FunctionUser dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
			This.ExposeToLua = ExposeToLua;
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.FunctionUser)dataObject );
		}
		protected void ToSerialization_Base( metadata.FunctionUser dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
			ExposeToLua = This.ExposeToLua;
		}
		
	}

	[XmlType("FunctionLua")]
	public class FunctionLua_Serialization : metadata.Function_Serialization
	{
		[XmlIgnore]
		metadata.FunctionLua This;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			stringToObject.Add( GuidStr.ToOptGuid(), This );	
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.FunctionLua)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.FunctionLua dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.FunctionLua dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.FunctionLua)dataObject );
		}
		protected void ToSerialization_Base( metadata.FunctionLua dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
		}
		
	}

	[XmlType("FunctionLuaCallCC")]
	public class FunctionLuaCallCC_Serialization : metadata.Function_Serialization
	{
		[XmlIgnore]
		metadata.FunctionLuaCallCC This;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			stringToObject.Add( GuidStr.ToOptGuid(), This );	
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.FunctionLuaCallCC)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.FunctionLuaCallCC dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.FunctionLuaCallCC dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.FunctionLuaCallCC)dataObject );
		}
		protected void ToSerialization_Base( metadata.FunctionLuaCallCC dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
		}
		
	}

	[XmlType("Argument")]
	public abstract class Argument_Serialization : core.SerializationObject
	{
		[XmlIgnore]
		metadata.Argument This;

		[XmlAttribute]
		[DefaultValue("arg")]
		public string Name = "arg";

		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.Argument)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.Argument dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.Argument dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
			This.Name = Name;
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.Argument)dataObject );
		}
		protected void ToSerialization_Base( metadata.Argument dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
			Name = This.Name;
		}
		
	}

	[XmlType("ArgumentsCollection")]
	public class ArgumentsCollection_Serialization : core.SerializationCollectionOf <metadata.Argument_Serialization>
	{
		[XmlIgnore]
		metadata.ArgumentsCollection This;

		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.ArgumentsCollection)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.ArgumentsCollection dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
			This.Clear();
			foreach( metadata.Argument_Serialization collectionElement in Values )
			{
				metadata.Argument dataCollectionElement = metadata.Serialization.ConstructData<metadata.Argument>( collectionElement.GetType() );
				collectionElement.FromSerializationConstruct( dataCollectionElement );
				This.Add( dataCollectionElement );
			}
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.ArgumentsCollection dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
			foreach( metadata.Argument_Serialization collectionElement in Values )
				collectionElement.FromSerialization( stringToObject );
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.ArgumentsCollection)dataObject );
		}
		protected void ToSerialization_Base( metadata.ArgumentsCollection dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
			Clear();
			foreach( metadata.Argument dataCollectionElement in This )
			{
				metadata.Argument_Serialization collectionElement = metadata.Serialization.ConstructSerialization<metadata.Argument_Serialization>( dataCollectionElement.GetType() );
				collectionElement.ToSerialization( dataCollectionElement );	
				Add( collectionElement );
			}
		}
		
	}

	[XmlType("ArgumentValue")]
	public class ArgumentValue_Serialization : metadata.Argument_Serialization
	{
		[XmlIgnore]
		metadata.ArgumentValue This;

		[XmlAttribute]
		[DefaultValue("")]
		public string Type;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.ArgumentValue)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.ArgumentValue dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.ArgumentValue dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
			This.Type = stringToObject.Fixup < metadata.Type >( Type.ToOptGuid() );
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.ArgumentValue)dataObject );
		}
		protected void ToSerialization_Base( metadata.ArgumentValue dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
			Type = ( This.Type == null ? "" : This.Type.Guid.ToOptString() );
		}
		
	}

	[XmlType("ArgumentReference")]
	public class ArgumentReference_Serialization : metadata.Argument_Serialization
	{
		[XmlIgnore]
		metadata.ArgumentReference This;

		[XmlAttribute]
		[DefaultValue("")]
		public string Type;

		public override void CreateGuidToObjectMapping ( core.StringToObject stringToObject ) 
		{
			CreateGuidToObjectMapping_Base( stringToObject );
		}
		protected override void CreateGuidToObjectMapping_Base ( core.StringToObject stringToObject )
		{
			base.CreateGuidToObjectMapping_Base( stringToObject );
		}
		
		public override void FromSerializationConstruct( core.DataObject dataObject )
		{
			FromSerializationConstruct_Base( (metadata.ArgumentReference)dataObject );
		}
		protected void FromSerializationConstruct_Base( metadata.ArgumentReference dataObject )
		{
			This = dataObject;
			base.FromSerializationConstruct_Base( This );
		}
		
		public override void FromSerialization( core.StringToObject stringToObject )
		{
			FromSerialization_Base( This, stringToObject );
		}
		protected void FromSerialization_Base( metadata.ArgumentReference dataObject, core.StringToObject stringToObject )
		{
			base.FromSerialization_Base( This, stringToObject );	
			This.Type = stringToObject.Fixup < metadata.MetadataClass >( Type.ToOptGuid() );
		}
		
		public override void ToSerialization( core.DataObject dataObject )
		{
			ToSerialization_Base( (metadata.ArgumentReference)dataObject );
		}
		protected void ToSerialization_Base( metadata.ArgumentReference dataObject )
		{
			This = dataObject;	
			base.ToSerialization_Base( This );
			Type = ( This.Type == null ? "" : This.Type.Guid.ToOptString() );
		}
		
	}

} /* namespace metadata */ 
