
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace reflection { 

	public abstract partial class Fundamental : reflection.Type
	{
	}

	public partial class FundamentalBool : reflection.Fundamental
	{
	}

	public partial class FundamentalString : reflection.Fundamental
	{
	}

	public partial class FundamentalInt : reflection.Fundamental
	{
	}

	public partial class FundamentalFloat : reflection.Fundamental
	{
	}

	public partial class FundamentalByte : reflection.Fundamental
	{
	}

	public partial class Enumeration : reflection.Type
	{
		public reflection.EnumeratorsCollection Enumerators = new reflection.EnumeratorsCollection();
	}

	public partial class Enumerator : core.DataObject
	{
		public string Name;
		public int IntegralValue;
	}

	public partial class EnumeratorsCollection : core.CollectionOf <reflection.Enumerator>
	{
	}

} /* namespace reflection */ 
