
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.IO;
using System.Xml.Serialization;
using System.ComponentModel;

[XmlType("Vec2")]
public class Vec2_Serialization : core.SerializationObject
{
	[XmlIgnore]
	Vec2 This;

	[XmlAttribute]
	public float x;

	[XmlAttribute]
	public float y;

	
	public override void FromSerializationConstruct( core.DataObject dataObject )
	{
		FromSerializationConstruct_Base( (Vec2)dataObject );
	}
	protected void FromSerializationConstruct_Base( Vec2 dataObject )
	{
		This = dataObject;
		base.FromSerializationConstruct_Base( This );
	}
	
	public override void FromSerialization( core.StringToObject stringToObject )
	{
		FromSerialization_Base( This, stringToObject );
	}
	protected void FromSerialization_Base( Vec2 dataObject, core.StringToObject stringToObject )
	{
		base.FromSerialization_Base( This, stringToObject );	
		This.x = x;
		This.y = y;
	}
	
	public override void ToSerialization( core.DataObject dataObject )
	{
		ToSerialization_Base( (Vec2)dataObject );
	}
	protected void ToSerialization_Base( Vec2 dataObject )
	{
		This = dataObject;	
		base.ToSerialization_Base( This );
		x = This.x;
		y = This.y;
	}
	
}

[XmlType("Vec3")]
public class Vec3_Serialization : core.SerializationObject
{
	[XmlIgnore]
	Vec3 This;

	[XmlAttribute]
	public float x;

	[XmlAttribute]
	public float y;

	[XmlAttribute]
	public float z;

	
	public override void FromSerializationConstruct( core.DataObject dataObject )
	{
		FromSerializationConstruct_Base( (Vec3)dataObject );
	}
	protected void FromSerializationConstruct_Base( Vec3 dataObject )
	{
		This = dataObject;
		base.FromSerializationConstruct_Base( This );
	}
	
	public override void FromSerialization( core.StringToObject stringToObject )
	{
		FromSerialization_Base( This, stringToObject );
	}
	protected void FromSerialization_Base( Vec3 dataObject, core.StringToObject stringToObject )
	{
		base.FromSerialization_Base( This, stringToObject );	
		This.x = x;
		This.y = y;
		This.z = z;
	}
	
	public override void ToSerialization( core.DataObject dataObject )
	{
		ToSerialization_Base( (Vec3)dataObject );
	}
	protected void ToSerialization_Base( Vec3 dataObject )
	{
		This = dataObject;	
		base.ToSerialization_Base( This );
		x = This.x;
		y = This.y;
		z = This.z;
	}
	
}

[XmlType("Vec4")]
public class Vec4_Serialization : core.SerializationObject
{
	[XmlIgnore]
	Vec4 This;

	[XmlAttribute]
	public float x;

	[XmlAttribute]
	public float y;

	[XmlAttribute]
	public float z;

	[XmlAttribute]
	public float w;

	
	public override void FromSerializationConstruct( core.DataObject dataObject )
	{
		FromSerializationConstruct_Base( (Vec4)dataObject );
	}
	protected void FromSerializationConstruct_Base( Vec4 dataObject )
	{
		This = dataObject;
		base.FromSerializationConstruct_Base( This );
	}
	
	public override void FromSerialization( core.StringToObject stringToObject )
	{
		FromSerialization_Base( This, stringToObject );
	}
	protected void FromSerialization_Base( Vec4 dataObject, core.StringToObject stringToObject )
	{
		base.FromSerialization_Base( This, stringToObject );	
		This.x = x;
		This.y = y;
		This.z = z;
		This.w = w;
	}
	
	public override void ToSerialization( core.DataObject dataObject )
	{
		ToSerialization_Base( (Vec4)dataObject );
	}
	protected void ToSerialization_Base( Vec4 dataObject )
	{
		This = dataObject;	
		base.ToSerialization_Base( This );
		x = This.x;
		y = This.y;
		z = This.z;
		w = This.w;
	}
	
}

[XmlType("Color")]
public class Color_Serialization : core.SerializationObject
{
	[XmlIgnore]
	Color This;

	[XmlAttribute]
	[DefaultValue(0)]
	public byte r = 0;

	[XmlAttribute]
	[DefaultValue(0)]
	public byte g = 0;

	[XmlAttribute]
	[DefaultValue(0)]
	public byte b = 0;

	[XmlAttribute]
	[DefaultValue(255)]
	public byte a = 255;

	
	public override void FromSerializationConstruct( core.DataObject dataObject )
	{
		FromSerializationConstruct_Base( (Color)dataObject );
	}
	protected void FromSerializationConstruct_Base( Color dataObject )
	{
		This = dataObject;
		base.FromSerializationConstruct_Base( This );
	}
	
	public override void FromSerialization( core.StringToObject stringToObject )
	{
		FromSerialization_Base( This, stringToObject );
	}
	protected void FromSerialization_Base( Color dataObject, core.StringToObject stringToObject )
	{
		base.FromSerialization_Base( This, stringToObject );	
		This.r = r;
		This.g = g;
		This.b = b;
		This.a = a;
	}
	
	public override void ToSerialization( core.DataObject dataObject )
	{
		ToSerialization_Base( (Color)dataObject );
	}
	protected void ToSerialization_Base( Color dataObject )
	{
		This = dataObject;	
		base.ToSerialization_Base( This );
		r = This.r;
		g = This.g;
		b = This.b;
		a = This.a;
	}
	
}

