
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

#include "Fundamental.h"

bool Vec2_ByteStream::ObjectFromByteStream( core::ByteStreamReader & stream, Vec2 & dataObject )
{
	float x; if ( !stream.ReadFloat32( x ) ) return false;
	dataObject.x = x;
	
	float y; if ( !stream.ReadFloat32( y ) ) return false;
	dataObject.y = y;
	
	return true;
}

bool Vec3_ByteStream::ObjectFromByteStream( core::ByteStreamReader & stream, Vec3 & dataObject )
{
	float x; if ( !stream.ReadFloat32( x ) ) return false;
	dataObject.x = x;
	
	float y; if ( !stream.ReadFloat32( y ) ) return false;
	dataObject.y = y;
	
	float z; if ( !stream.ReadFloat32( z ) ) return false;
	dataObject.z = z;
	
	return true;
}

bool Vec4_ByteStream::ObjectFromByteStream( core::ByteStreamReader & stream, Vec4 & dataObject )
{
	float x; if ( !stream.ReadFloat32( x ) ) return false;
	dataObject.x = x;
	
	float y; if ( !stream.ReadFloat32( y ) ) return false;
	dataObject.y = y;
	
	float z; if ( !stream.ReadFloat32( z ) ) return false;
	dataObject.z = z;
	
	float w; if ( !stream.ReadFloat32( w ) ) return false;
	dataObject.w = w;
	
	return true;
}

bool Color_ByteStream::ObjectFromByteStream( core::ByteStreamReader & stream, Color & dataObject )
{
	core::uint8 r; if ( !stream.ReadUint8( r ) ) return false;
	dataObject.r = r;
	
	core::uint8 g; if ( !stream.ReadUint8( g ) ) return false;
	dataObject.g = g;
	
	core::uint8 b; if ( !stream.ReadUint8( b ) ) return false;
	dataObject.b = b;
	
	core::uint8 a; if ( !stream.ReadUint8( a ) ) return false;
	dataObject.a = a;
	
	return true;
}

