
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

#include "Fundamental.h"

#include "..\..\Reflection.h"

#include "Fundamental.Reflection.h"

// depends on parent/reference files
// depends on reflection files

class Vec2_Member_x : public reflection::Value
{
public:
	Vec2_Member_x()
	{
		Set_Guid("47c8e2e3-9d63-4bbd-b235-ce3d714a85b6");
		Set_Name("x");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Vec2 * pThis = core::polymorphic_downcast< Vec2 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed const * pDataObject = core::polymorphic_downcast < float_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->x = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Vec2 const * pThis = core::polymorphic_downcast< Vec2 const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed * pDataObject = CORE_NEW float_Boxed();
		pDataObject->value = pThis->x;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Vec2 * pThis = core::polymorphic_downcast< Vec2 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::float32 value; if ( !stream.ReadFloat32( value ) ) return false;
		pThis->x = value;
		return true;
	}	
};

class Vec2_Member_y : public reflection::Value
{
public:
	Vec2_Member_y()
	{
		Set_Guid("a3d5fa31-c150-47f0-8151-a9097801901b");
		Set_Name("y");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Vec2 * pThis = core::polymorphic_downcast< Vec2 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed const * pDataObject = core::polymorphic_downcast < float_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->y = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Vec2 const * pThis = core::polymorphic_downcast< Vec2 const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed * pDataObject = CORE_NEW float_Boxed();
		pDataObject->value = pThis->y;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Vec2 * pThis = core::polymorphic_downcast< Vec2 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::float32 value; if ( !stream.ReadFloat32( value ) ) return false;
		pThis->y = value;
		return true;
	}	
};


Vec2_Reflection::Vec2_Reflection()
{
	Set_Guid("d52e959b-5ebf-4a6e-a42a-d0c234de2bd9");
	Set_TypeName("Vec2");	
	Get_Members().Add( CORE_NEW Vec2_Member_x() );
	Get_Members().Add( CORE_NEW Vec2_Member_y() );
}

void Vec2_Reflection::CopyObjectDataFromTo( Vec2 const & from, Vec2 & to )
{
	// TODO: implement
}


class Vec3_Member_x : public reflection::Value
{
public:
	Vec3_Member_x()
	{
		Set_Guid("5cd0c314-9a3c-41c2-b74a-73f4dcbcb285");
		Set_Name("x");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Vec3 * pThis = core::polymorphic_downcast< Vec3 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed const * pDataObject = core::polymorphic_downcast < float_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->x = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Vec3 const * pThis = core::polymorphic_downcast< Vec3 const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed * pDataObject = CORE_NEW float_Boxed();
		pDataObject->value = pThis->x;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Vec3 * pThis = core::polymorphic_downcast< Vec3 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::float32 value; if ( !stream.ReadFloat32( value ) ) return false;
		pThis->x = value;
		return true;
	}	
};

class Vec3_Member_y : public reflection::Value
{
public:
	Vec3_Member_y()
	{
		Set_Guid("bb545baf-3aa6-4785-803a-ef3b409f74ea");
		Set_Name("y");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Vec3 * pThis = core::polymorphic_downcast< Vec3 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed const * pDataObject = core::polymorphic_downcast < float_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->y = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Vec3 const * pThis = core::polymorphic_downcast< Vec3 const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed * pDataObject = CORE_NEW float_Boxed();
		pDataObject->value = pThis->y;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Vec3 * pThis = core::polymorphic_downcast< Vec3 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::float32 value; if ( !stream.ReadFloat32( value ) ) return false;
		pThis->y = value;
		return true;
	}	
};

class Vec3_Member_z : public reflection::Value
{
public:
	Vec3_Member_z()
	{
		Set_Guid("8f4fd682-b4b1-40c5-ae6c-9e7ee4ff00d2");
		Set_Name("z");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Vec3 * pThis = core::polymorphic_downcast< Vec3 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed const * pDataObject = core::polymorphic_downcast < float_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->z = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Vec3 const * pThis = core::polymorphic_downcast< Vec3 const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed * pDataObject = CORE_NEW float_Boxed();
		pDataObject->value = pThis->z;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Vec3 * pThis = core::polymorphic_downcast< Vec3 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::float32 value; if ( !stream.ReadFloat32( value ) ) return false;
		pThis->z = value;
		return true;
	}	
};


Vec3_Reflection::Vec3_Reflection()
{
	Set_Guid("112dfe1c-6c21-482d-8836-dd51a3b900d5");
	Set_TypeName("Vec3");	
	Get_Members().Add( CORE_NEW Vec3_Member_x() );
	Get_Members().Add( CORE_NEW Vec3_Member_y() );
	Get_Members().Add( CORE_NEW Vec3_Member_z() );
}

void Vec3_Reflection::CopyObjectDataFromTo( Vec3 const & from, Vec3 & to )
{
	// TODO: implement
}


class Vec4_Member_x : public reflection::Value
{
public:
	Vec4_Member_x()
	{
		Set_Guid("c24e6d22-9eff-47a3-b54c-83b52839e82a");
		Set_Name("x");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Vec4 * pThis = core::polymorphic_downcast< Vec4 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed const * pDataObject = core::polymorphic_downcast < float_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->x = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Vec4 const * pThis = core::polymorphic_downcast< Vec4 const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed * pDataObject = CORE_NEW float_Boxed();
		pDataObject->value = pThis->x;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Vec4 * pThis = core::polymorphic_downcast< Vec4 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::float32 value; if ( !stream.ReadFloat32( value ) ) return false;
		pThis->x = value;
		return true;
	}	
};

class Vec4_Member_y : public reflection::Value
{
public:
	Vec4_Member_y()
	{
		Set_Guid("a78486e0-f79a-4213-a9d9-b6e9c92dead4");
		Set_Name("y");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Vec4 * pThis = core::polymorphic_downcast< Vec4 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed const * pDataObject = core::polymorphic_downcast < float_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->y = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Vec4 const * pThis = core::polymorphic_downcast< Vec4 const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed * pDataObject = CORE_NEW float_Boxed();
		pDataObject->value = pThis->y;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Vec4 * pThis = core::polymorphic_downcast< Vec4 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::float32 value; if ( !stream.ReadFloat32( value ) ) return false;
		pThis->y = value;
		return true;
	}	
};

class Vec4_Member_z : public reflection::Value
{
public:
	Vec4_Member_z()
	{
		Set_Guid("11eb8741-b3ab-473f-8d60-a914a1428ca4");
		Set_Name("z");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Vec4 * pThis = core::polymorphic_downcast< Vec4 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed const * pDataObject = core::polymorphic_downcast < float_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->z = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Vec4 const * pThis = core::polymorphic_downcast< Vec4 const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed * pDataObject = CORE_NEW float_Boxed();
		pDataObject->value = pThis->z;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Vec4 * pThis = core::polymorphic_downcast< Vec4 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::float32 value; if ( !stream.ReadFloat32( value ) ) return false;
		pThis->z = value;
		return true;
	}	
};

class Vec4_Member_w : public reflection::Value
{
public:
	Vec4_Member_w()
	{
		Set_Guid("79afac39-0db8-4b55-90ba-37cd72020b5c");
		Set_Name("w");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Vec4 * pThis = core::polymorphic_downcast< Vec4 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed const * pDataObject = core::polymorphic_downcast < float_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->w = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Vec4 const * pThis = core::polymorphic_downcast< Vec4 const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		float_Boxed * pDataObject = CORE_NEW float_Boxed();
		pDataObject->value = pThis->w;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Vec4 * pThis = core::polymorphic_downcast< Vec4 * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::float32 value; if ( !stream.ReadFloat32( value ) ) return false;
		pThis->w = value;
		return true;
	}	
};


Vec4_Reflection::Vec4_Reflection()
{
	Set_Guid("9d2791fa-97bd-4f43-8ea0-af0462b7cd69");
	Set_TypeName("Vec4");	
	Get_Members().Add( CORE_NEW Vec4_Member_x() );
	Get_Members().Add( CORE_NEW Vec4_Member_y() );
	Get_Members().Add( CORE_NEW Vec4_Member_z() );
	Get_Members().Add( CORE_NEW Vec4_Member_w() );
}

void Vec4_Reflection::CopyObjectDataFromTo( Vec4 const & from, Vec4 & to )
{
	// TODO: implement
}


class Color_Member_r : public reflection::Value
{
public:
	Color_Member_r()
	{
		Set_Guid("77d27a3d-55c3-4593-a018-489b609bff87");
		Set_Name("r");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Color * pThis = core::polymorphic_downcast< Color * >( &ThisUnityped );
		if ( !pThis )
			return false;
		byte_Boxed const * pDataObject = core::polymorphic_downcast < byte_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->r = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Color const * pThis = core::polymorphic_downcast< Color const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		byte_Boxed * pDataObject = CORE_NEW byte_Boxed();
		pDataObject->value = pThis->r;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Color * pThis = core::polymorphic_downcast< Color * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::uint8 value; if ( !stream.ReadUint8( value ) ) return false;
		pThis->r = value;
		return true;
	}	
};

class Color_Member_g : public reflection::Value
{
public:
	Color_Member_g()
	{
		Set_Guid("3b535228-8210-4a08-9a0c-87d4b6711592");
		Set_Name("g");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Color * pThis = core::polymorphic_downcast< Color * >( &ThisUnityped );
		if ( !pThis )
			return false;
		byte_Boxed const * pDataObject = core::polymorphic_downcast < byte_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->g = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Color const * pThis = core::polymorphic_downcast< Color const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		byte_Boxed * pDataObject = CORE_NEW byte_Boxed();
		pDataObject->value = pThis->g;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Color * pThis = core::polymorphic_downcast< Color * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::uint8 value; if ( !stream.ReadUint8( value ) ) return false;
		pThis->g = value;
		return true;
	}	
};

class Color_Member_b : public reflection::Value
{
public:
	Color_Member_b()
	{
		Set_Guid("786c248c-59bb-4c30-8407-1fed57139019");
		Set_Name("b");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Color * pThis = core::polymorphic_downcast< Color * >( &ThisUnityped );
		if ( !pThis )
			return false;
		byte_Boxed const * pDataObject = core::polymorphic_downcast < byte_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->b = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Color const * pThis = core::polymorphic_downcast< Color const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		byte_Boxed * pDataObject = CORE_NEW byte_Boxed();
		pDataObject->value = pThis->b;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Color * pThis = core::polymorphic_downcast< Color * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::uint8 value; if ( !stream.ReadUint8( value ) ) return false;
		pThis->b = value;
		return true;
	}	
};

class Color_Member_a : public reflection::Value
{
public:
	Color_Member_a()
	{
		Set_Guid("0be7832e-2fdc-4388-bb01-e0efacd753e5");
		Set_Name("a");
	}
	virtual bool SetObjectValue( core::DataObject & ThisUnityped, core::DataObject * pDataObjectUnityped ) const
	{
		Color * pThis = core::polymorphic_downcast< Color * >( &ThisUnityped );
		if ( !pThis )
			return false;
		byte_Boxed const * pDataObject = core::polymorphic_downcast < byte_Boxed const * > ( pDataObjectUnityped );
		if ( !pDataObject )
			return false;
		pThis->a = pDataObject->value;
		return true;
	}
	virtual bool GetObjectValue( core::DataObject const & ThisUnityped, core::DataObject * & pDataObjectUnityped ) const
	{
		Color const * pThis = core::polymorphic_downcast< Color const * >( &ThisUnityped );
		if ( !pThis )
			return false;
		byte_Boxed * pDataObject = CORE_NEW byte_Boxed();
		pDataObject->value = pThis->a;
		pDataObjectUnityped = pDataObject;
		return true;
	}
	virtual bool SetObjectValue_FromByteStream( core::DataObject & ThisUnityped, core::ByteStreamReader & stream ) const
	{
		Color * pThis = core::polymorphic_downcast< Color * >( &ThisUnityped );
		if ( !pThis )
			return false;
		core::uint8 value; if ( !stream.ReadUint8( value ) ) return false;
		pThis->a = value;
		return true;
	}	
};


Color_Reflection::Color_Reflection()
{
	Set_Guid("bfe3b0a7-c2d7-4511-ac3e-60145bb18632");
	Set_TypeName("Color");	
	Get_Members().Add( CORE_NEW Color_Member_r() );
	Get_Members().Add( CORE_NEW Color_Member_g() );
	Get_Members().Add( CORE_NEW Color_Member_b() );
	Get_Members().Add( CORE_NEW Color_Member_a() );
}

void Color_Reflection::CopyObjectDataFromTo( Color const & from, Color & to )
{
	// TODO: implement
}


