
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

#ifndef Metadata_Engine_Fundamental_Partial_h
#define Metadata_Engine_Fundamental_Partial_h

#include "..\..\Core.h"

// forward declarations from other files


// dependencies


// forward declarations

class Vec2; class Vec2_Boxed;
class Vec3; class Vec3_Boxed;
class Vec4; class Vec4_Boxed;
class Color; class Color_Boxed;

// classes

namespace Vec2_ByteStream
{
	bool ObjectFromByteStream( core::ByteStreamReader & stream, Vec2 & dataObject );
};

namespace Vec3_ByteStream
{
	bool ObjectFromByteStream( core::ByteStreamReader & stream, Vec3 & dataObject );
};

namespace Vec4_ByteStream
{
	bool ObjectFromByteStream( core::ByteStreamReader & stream, Vec4 & dataObject );
};

namespace Color_ByteStream
{
	bool ObjectFromByteStream( core::ByteStreamReader & stream, Color & dataObject );
};


#endif // Metadata_Engine_Fundamental_Partial_h
