
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace metadata { 

	public partial class MetadataFile : core.ReferenceObject
	{
		public string Name = "File";
		public metadata.MetadataFolder Parent;
		public string Namespace = "";
		public metadata.MetadataFileContent Content;
		public bool GenerateGui = true;
		public bool GenerateSerialization = true;
		public string RelativeName { get { return Parent.RelativeName + @"\" + Name; } }
		public string FullName { get { return Parent.FullName + @"\" + Name; } }
		public string RootFolderRelativeName { get { return Parent.RootFolderRelativeName + Name; } }
	}

	public partial class MetadataFilesCollection : core.CollectionOf <metadata.MetadataFile>
	{
	}

	public partial class MetadataFolder : core.ReferenceObject
	{
		public string Name = "Folder";
		public metadata.MetadataFolder Parent;
		public metadata.MetadataProject ParentProject;
		public string Namespace = "";
		public metadata.MetadataFoldersCollection Folders = new metadata.MetadataFoldersCollection();
		public metadata.MetadataFilesCollection Files = new metadata.MetadataFilesCollection();
		public string RelativeName { get { return (Parent == null ? "" : Parent.RelativeName + @"\") + Name; } }
		public string RootFolderRelativeName { get { return Parent == null ? "" : Parent.RootFolderRelativeName + Name + @"\"; } }
		public string FullName { get { return (Parent == null ? ParentProject.ProjectPath : Parent.FullName ) + @"\" + Name; } }
		
		public metadata.MetadataFolder MetadataFolderCreate(string name)
		{
			metadata.MetadataFolder collectionElement = new metadata.MetadataFolder();
			collectionElement.Parent = this;
			collectionElement.Name = name;
			collectionElement.Guid = Guid.NewGuid();
			
			Folders.Add(collectionElement);
			return collectionElement;
		}
		
		public metadata.MetadataFile MetadataFileCreate(string name)
		{
			metadata.MetadataFile collectionElement = new metadata.MetadataFile();
			collectionElement.Parent = this;
			collectionElement.Name = name;
			collectionElement.Guid = Guid.NewGuid();
			
			Files.Add(collectionElement);
			return collectionElement;
		}
		
		public metadata.MetadataFolder MetadataFolderGet( string name )
		{
			metadata.MetadataFolder collectionElement = Folders.Find( f => f.Name == name );
			if ( collectionElement == null )
				throw new core.TreePathException( name );
			return collectionElement;
		}
		
		public metadata.MetadataFile MetadataFileGet( string name )
		{
			metadata.MetadataFile collectionElement = Files.Find( f => f.Name == name );
			if ( collectionElement == null )
				throw new core.TreePathException( name );
			return collectionElement;
		}
	}

	public partial class MetadataFoldersCollection : core.CollectionOf <metadata.MetadataFolder>
	{
	}

	public partial class MetadataMemberGroup : core.ReferenceObject
	{
		public string Name = "Group";
		public string PartialFileExtension;
	}

	public partial class MemberGroupsCollection : core.CollectionOf <metadata.MetadataMemberGroup>
	{
	}

	public partial class MetadataProject : core.DataObject
	{
		public string CoreNamespace = "core";
		public metadata.MetadataFolder Metadata = new metadata.MetadataFolder ();
		public metadata.MemberGroupsCollection MemberGroups = new metadata.MemberGroupsCollection();
		public string ProjectPath;
		public string ProjectName;
	}

} /* namespace metadata */ 
