
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace metadata { 

	public enum RemoteType
	{
		None = 0,
		Server = 1,
		Client = 2,
	};
	
	public class RemoteType_Boxed : core.FundamentalBoxed
	{
		public RemoteType value = RemoteType.None;
	};
	
	public abstract partial class Function : metadata.Member
	{
		public metadata.Argument Result;
		public metadata.ArgumentsCollection Arguments = new metadata.ArgumentsCollection();
		public metadata.RemoteType Remote = metadata.RemoteType.None;
		public bool IsStatic = false;
	}

	public partial class FunctionUser : metadata.Function
	{
		public bool ExposeToLua = false;
	}

	public partial class FunctionLua : metadata.Function
	{
	}

	public partial class FunctionLuaCallCC : metadata.Function
	{
	}

	public abstract partial class Argument : core.DataObject
	{
		public string Name = "arg";
	}

	public partial class ArgumentsCollection : core.CollectionOf <metadata.Argument>
	{
	}

	public partial class ArgumentValue : metadata.Argument
	{
		public metadata.Type Type;
	}

	public partial class ArgumentReference : metadata.Argument
	{
		public metadata.MetadataClass Type;
	}

} /* namespace metadata */ 
