
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace reflection { 

	public enum RemoteType
	{
		None = 0,
		Server = 1,
		Client = 2,
	};
	
	public class RemoteType_Boxed : core.FundamentalBoxed
	{
		public RemoteType value = RemoteType.None;
	};
	
	public abstract partial class Function : reflection.Member
	{
		public reflection.Argument Result;
		public reflection.ArgumentsCollection Arguments = new reflection.ArgumentsCollection();
		public reflection.RemoteType Remote = reflection.RemoteType.None;
		public bool IsStatic = false;
	}

	public partial class FunctionUser : reflection.Function
	{
		public bool ExposeToLua = false;
	}

	public partial class FunctionLua : reflection.Function
	{
	}

	public partial class FunctionLuaCallCC : reflection.Function
	{
	}

	public abstract partial class Argument : core.DataObject
	{
		public string Name = "arg";
	}

	public partial class ArgumentsCollection : core.CollectionOf <reflection.Argument>
	{
	}

	public partial class ArgumentValue : reflection.Argument
	{
		public reflection.Type Type;
	}

	public partial class ArgumentReference : reflection.Argument
	{
		public reflection.MetadataClass Type;
	}

} /* namespace reflection */ 
