
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

public class Vec2_Member_x : reflection.Value
{
	public static Vec2_Member_x Member = new Vec2_Member_x 
	{ 
		Guid = new System.Guid("47c8e2e3-9d63-4bbd-b235-ce3d714a85b6") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Vec2 This = ThisUnityped as Vec2;
		if ( This == null )
			return false;
		
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;

		This.x = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Vec2 This = ThisUnityped as Vec2;
		if ( This == null )
			return false;

		float_Boxed dataObject = new float_Boxed();
		dataObject.value = This.x;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteFloat32( dataObject.value );
		
		return true;
	}	
};

public class Vec2_Member_y : reflection.Value
{
	public static Vec2_Member_y Member = new Vec2_Member_y 
	{ 
		Guid = new System.Guid("a3d5fa31-c150-47f0-8151-a9097801901b") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Vec2 This = ThisUnityped as Vec2;
		if ( This == null )
			return false;
		
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;

		This.y = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Vec2 This = ThisUnityped as Vec2;
		if ( This == null )
			return false;

		float_Boxed dataObject = new float_Boxed();
		dataObject.value = This.y;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteFloat32( dataObject.value );
		
		return true;
	}	
};

public class Vec2_Reflection : reflection.MetadataClass
{
	public static Vec2_Reflection MetadataClass = new Vec2_Reflection 
	{ 
		  Guid = new System.Guid("d52e959b-5ebf-4a6e-a42a-d0c234de2bd9")
	};
	
	public Vec2_Reflection()
	{
		Members.Add( new Vec2_Member_x() );
		Members.Add( new Vec2_Member_y() );
	}
	
	public override core.DataObject New() 
	{ 
		return null; 
	}

	public override void Delete( core.DataObject dataObject ) 
	{ 
	}
};


public class Vec3_Member_x : reflection.Value
{
	public static Vec3_Member_x Member = new Vec3_Member_x 
	{ 
		Guid = new System.Guid("5cd0c314-9a3c-41c2-b74a-73f4dcbcb285") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Vec3 This = ThisUnityped as Vec3;
		if ( This == null )
			return false;
		
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;

		This.x = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Vec3 This = ThisUnityped as Vec3;
		if ( This == null )
			return false;

		float_Boxed dataObject = new float_Boxed();
		dataObject.value = This.x;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteFloat32( dataObject.value );
		
		return true;
	}	
};

public class Vec3_Member_y : reflection.Value
{
	public static Vec3_Member_y Member = new Vec3_Member_y 
	{ 
		Guid = new System.Guid("bb545baf-3aa6-4785-803a-ef3b409f74ea") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Vec3 This = ThisUnityped as Vec3;
		if ( This == null )
			return false;
		
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;

		This.y = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Vec3 This = ThisUnityped as Vec3;
		if ( This == null )
			return false;

		float_Boxed dataObject = new float_Boxed();
		dataObject.value = This.y;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteFloat32( dataObject.value );
		
		return true;
	}	
};

public class Vec3_Member_z : reflection.Value
{
	public static Vec3_Member_z Member = new Vec3_Member_z 
	{ 
		Guid = new System.Guid("8f4fd682-b4b1-40c5-ae6c-9e7ee4ff00d2") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Vec3 This = ThisUnityped as Vec3;
		if ( This == null )
			return false;
		
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;

		This.z = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Vec3 This = ThisUnityped as Vec3;
		if ( This == null )
			return false;

		float_Boxed dataObject = new float_Boxed();
		dataObject.value = This.z;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteFloat32( dataObject.value );
		
		return true;
	}	
};

public class Vec3_Reflection : reflection.MetadataClass
{
	public static Vec3_Reflection MetadataClass = new Vec3_Reflection 
	{ 
		  Guid = new System.Guid("112dfe1c-6c21-482d-8836-dd51a3b900d5")
	};
	
	public Vec3_Reflection()
	{
		Members.Add( new Vec3_Member_x() );
		Members.Add( new Vec3_Member_y() );
		Members.Add( new Vec3_Member_z() );
	}
	
	public override core.DataObject New() 
	{ 
		return null; 
	}

	public override void Delete( core.DataObject dataObject ) 
	{ 
	}
};


public class Vec4_Member_x : reflection.Value
{
	public static Vec4_Member_x Member = new Vec4_Member_x 
	{ 
		Guid = new System.Guid("c24e6d22-9eff-47a3-b54c-83b52839e82a") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Vec4 This = ThisUnityped as Vec4;
		if ( This == null )
			return false;
		
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;

		This.x = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Vec4 This = ThisUnityped as Vec4;
		if ( This == null )
			return false;

		float_Boxed dataObject = new float_Boxed();
		dataObject.value = This.x;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteFloat32( dataObject.value );
		
		return true;
	}	
};

public class Vec4_Member_y : reflection.Value
{
	public static Vec4_Member_y Member = new Vec4_Member_y 
	{ 
		Guid = new System.Guid("a78486e0-f79a-4213-a9d9-b6e9c92dead4") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Vec4 This = ThisUnityped as Vec4;
		if ( This == null )
			return false;
		
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;

		This.y = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Vec4 This = ThisUnityped as Vec4;
		if ( This == null )
			return false;

		float_Boxed dataObject = new float_Boxed();
		dataObject.value = This.y;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteFloat32( dataObject.value );
		
		return true;
	}	
};

public class Vec4_Member_z : reflection.Value
{
	public static Vec4_Member_z Member = new Vec4_Member_z 
	{ 
		Guid = new System.Guid("11eb8741-b3ab-473f-8d60-a914a1428ca4") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Vec4 This = ThisUnityped as Vec4;
		if ( This == null )
			return false;
		
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;

		This.z = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Vec4 This = ThisUnityped as Vec4;
		if ( This == null )
			return false;

		float_Boxed dataObject = new float_Boxed();
		dataObject.value = This.z;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteFloat32( dataObject.value );
		
		return true;
	}	
};

public class Vec4_Member_w : reflection.Value
{
	public static Vec4_Member_w Member = new Vec4_Member_w 
	{ 
		Guid = new System.Guid("79afac39-0db8-4b55-90ba-37cd72020b5c") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Vec4 This = ThisUnityped as Vec4;
		if ( This == null )
			return false;
		
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;

		This.w = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Vec4 This = ThisUnityped as Vec4;
		if ( This == null )
			return false;

		float_Boxed dataObject = new float_Boxed();
		dataObject.value = This.w;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteFloat32( dataObject.value );
		
		return true;
	}	
};

public class Vec4_Reflection : reflection.MetadataClass
{
	public static Vec4_Reflection MetadataClass = new Vec4_Reflection 
	{ 
		  Guid = new System.Guid("9d2791fa-97bd-4f43-8ea0-af0462b7cd69")
	};
	
	public Vec4_Reflection()
	{
		Members.Add( new Vec4_Member_x() );
		Members.Add( new Vec4_Member_y() );
		Members.Add( new Vec4_Member_z() );
		Members.Add( new Vec4_Member_w() );
	}
	
	public override core.DataObject New() 
	{ 
		return null; 
	}

	public override void Delete( core.DataObject dataObject ) 
	{ 
	}
};


public class Color_Member_r : reflection.Value
{
	public static Color_Member_r Member = new Color_Member_r 
	{ 
		Guid = new System.Guid("77d27a3d-55c3-4593-a018-489b609bff87") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Color This = ThisUnityped as Color;
		if ( This == null )
			return false;
		
		byte_Boxed dataObject = dataObjectUnityped as byte_Boxed;		
		if ( dataObject == null )
			return false;

		This.r = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Color This = ThisUnityped as Color;
		if ( This == null )
			return false;

		byte_Boxed dataObject = new byte_Boxed();
		dataObject.value = This.r;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		byte_Boxed dataObject = dataObjectUnityped as byte_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteUint8( dataObject.value );
		
		return true;
	}	
};

public class Color_Member_g : reflection.Value
{
	public static Color_Member_g Member = new Color_Member_g 
	{ 
		Guid = new System.Guid("3b535228-8210-4a08-9a0c-87d4b6711592") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Color This = ThisUnityped as Color;
		if ( This == null )
			return false;
		
		byte_Boxed dataObject = dataObjectUnityped as byte_Boxed;		
		if ( dataObject == null )
			return false;

		This.g = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Color This = ThisUnityped as Color;
		if ( This == null )
			return false;

		byte_Boxed dataObject = new byte_Boxed();
		dataObject.value = This.g;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		byte_Boxed dataObject = dataObjectUnityped as byte_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteUint8( dataObject.value );
		
		return true;
	}	
};

public class Color_Member_b : reflection.Value
{
	public static Color_Member_b Member = new Color_Member_b 
	{ 
		Guid = new System.Guid("786c248c-59bb-4c30-8407-1fed57139019") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Color This = ThisUnityped as Color;
		if ( This == null )
			return false;
		
		byte_Boxed dataObject = dataObjectUnityped as byte_Boxed;		
		if ( dataObject == null )
			return false;

		This.b = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Color This = ThisUnityped as Color;
		if ( This == null )
			return false;

		byte_Boxed dataObject = new byte_Boxed();
		dataObject.value = This.b;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		byte_Boxed dataObject = dataObjectUnityped as byte_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteUint8( dataObject.value );
		
		return true;
	}	
};

public class Color_Member_a : reflection.Value
{
	public static Color_Member_a Member = new Color_Member_a 
	{ 
		Guid = new System.Guid("0be7832e-2fdc-4388-bb01-e0efacd753e5") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		Color This = ThisUnityped as Color;
		if ( This == null )
			return false;
		
		byte_Boxed dataObject = dataObjectUnityped as byte_Boxed;		
		if ( dataObject == null )
			return false;

		This.a = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		Color This = ThisUnityped as Color;
		if ( This == null )
			return false;

		byte_Boxed dataObject = new byte_Boxed();
		dataObject.value = This.a;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		byte_Boxed dataObject = dataObjectUnityped as byte_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteUint8( dataObject.value );
		
		return true;
	}	
};

public class Color_Reflection : reflection.MetadataClass
{
	public static Color_Reflection MetadataClass = new Color_Reflection 
	{ 
		  Guid = new System.Guid("bfe3b0a7-c2d7-4511-ac3e-60145bb18632")
	};
	
	public Color_Reflection()
	{
		Members.Add( new Color_Member_r() );
		Members.Add( new Color_Member_g() );
		Members.Add( new Color_Member_b() );
		Members.Add( new Color_Member_a() );
	}
	
	public override core.DataObject New() 
	{ 
		return null; 
	}

	public override void Delete( core.DataObject dataObject ) 
	{ 
	}
};


