
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

public class bool_Boxed : core.FundamentalBoxed
{
	public bool value;
}

public class float_Boxed : core.FundamentalBoxed
{
	public float value;
}

public class int_Boxed : core.FundamentalBoxed
{
	public int value;
}

public class string_Boxed : core.FundamentalBoxed
{
	public string value;
}

public class byte_Boxed : core.FundamentalBoxed
{
	public byte value;
}

public partial class Vec2 : core.DataObject
{
	public float x;
	public float y;
}

public partial class Vec3 : core.DataObject
{
	public float x;
	public float y;
	public float z;
}

public partial class Vec4 : core.DataObject
{
	public float x;
	public float y;
	public float z;
	public float w;
}

public partial class Color : core.DataObject
{
	public byte r = 0;
	public byte g = 0;
	public byte b = 0;
	public byte a = 255;
}

