
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace game { 

	public partial class Globals : core.ReferenceObject
	{
		public string name = "Globals";
		public game.Game parent;
		public string RelativeName { get { return name; } }
		public string RootFolderRelativeName { get { return name + @"\"; } }
		public string FullName { get { return parent.ProjectPath + @"\" + name; } }
	}

} /* namespace game */ 
