
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace gui { 

	public partial class Gui : core.ReferenceObject
	{
		public string name = "Gui";
		public gui.GuiMainMenu mainMenu = new gui.GuiMainMenu ();
		public gui.GuiGame game = new gui.GuiGame ();
		public game.Game parent;
		public string RelativeName { get { return name; } }
		public string RootFolderRelativeName { get { return name + @"\"; } }
		public string FullName { get { return parent.ProjectPath + @"\" + name; } }
	}

	public partial class GuiCommon : core.ReferenceObject, core.IFolderStorageObject
	{
		public string name = "Common";
		public gui.GuiFilesCollection files = new gui.GuiFilesCollection();
		public gui.Gui parent;
		public string RelativeName { get { return (parent == null ? "" : parent.RelativeName + @"\") + name; } }
		public string RootFolderRelativeName { get { return parent == null ? "" : parent.RootFolderRelativeName + name + @"\"; } }
		public string FullName { get { return parent.FullName + @"\" + name; } }
		
		public gui.GuiFile GuiFileCreate(string name)
		{
			gui.GuiFile collectionElement = new gui.GuiFile();
			collectionElement.parent = this;
			collectionElement.name = name;
			collectionElement.Guid = Guid.NewGuid();
			
			files.Add(collectionElement);
			return collectionElement;
		}
		
		public gui.GuiFile GuiFileGet( string name )
		{
			gui.GuiFile collectionElement = files.Find( f => f.name == name );
			if ( collectionElement == null )
				throw new core.TreePathException( name );
			return collectionElement;
		}
	}

	public partial class GuiMainMenu : gui.GuiCommon, core.IFolderStorageObject
	{
	}

	public partial class GuiGame : gui.GuiCommon, core.IFolderStorageObject
	{
	}

	public partial class GuiFile : core.ReferenceObject
	{
		public gui.Window mainWindow;
		public gui.GuiCommon parent;
		public string name = "File";
		public string RelativeName { get { return parent.RelativeName + @"\" + name; } }
		public string FullName { get { return parent.FullName + @"\" + name; } }
		public string RootFolderRelativeName { get { return parent.RootFolderRelativeName + name; } }
	}

	public partial class GuiFilesCollection : core.CollectionOf <gui.GuiFile>
	{
	}

} /* namespace gui */ 
