
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

namespace gui { 

public class Gui_Member_name : reflection.ValueName
{
	public static Gui_Member_name Member = new Gui_Member_name 
	{ 
		Guid = new System.Guid("c98d505b-8cdf-4138-b78a-c242b861180d") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		gui.Gui This = ThisUnityped as gui.Gui;
		if ( This == null )
			return false;
		
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;

		This.name = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		gui.Gui This = ThisUnityped as gui.Gui;
		if ( This == null )
			return false;

		string_Boxed dataObject = new string_Boxed();
		dataObject.value = This.name;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteBytes( System.Text.Encoding.ASCII.GetBytes( dataObject.value ) );
		
		return true;
	}	
};

public class Gui_Member_mainMenu : reflection.Value
{
	public static Gui_Member_mainMenu Member = new Gui_Member_mainMenu 
	{ 
		Guid = new System.Guid("ce028e20-7890-49dc-a991-a1ef29cdf910") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		gui.Gui This = ThisUnityped as gui.Gui;
		if ( This == null )
			return false;
			
		gui.GuiMainMenu dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as gui.GuiMainMenu;
			if ( dataObject == null )
				return false;
		}		
		This.mainMenu = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		gui.Gui This = ThisUnityped as gui.Gui;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.mainMenu;
		return true;	
	}
};

public class Gui_Member_game : reflection.Value
{
	public static Gui_Member_game Member = new Gui_Member_game 
	{ 
		Guid = new System.Guid("23ec491f-43b3-4128-834d-8ead43e294ca") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		gui.Gui This = ThisUnityped as gui.Gui;
		if ( This == null )
			return false;
			
		gui.GuiGame dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as gui.GuiGame;
			if ( dataObject == null )
				return false;
		}		
		This.game = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		gui.Gui This = ThisUnityped as gui.Gui;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.game;
		return true;	
	}
};

public class Gui_Member_parent : reflection.ParentReference
{
	public static Gui_Member_parent Member = new Gui_Member_parent 
	{ 
		Guid = new System.Guid("6ef7a615-f89f-4d7b-9485-64b1855825ad") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		gui.Gui This = ThisUnityped as gui.Gui;
		if ( This == null )
			return false;
			
		game.Game dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as game.Game;
			if ( dataObject == null )
				return false;
		}		
		This.parent = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		gui.Gui This = ThisUnityped as gui.Gui;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.parent;
		return true;	
	}
};

public class Gui_Reflection : reflection.FolderClass
{
	public static Gui_Reflection MetadataClass = new Gui_Reflection 
	{ 
		  Guid = new System.Guid("4e5f2dd2-3b2b-4c44-8620-262be737f924")
	};
	
	public Gui_Reflection()
	{
		Members.Add( new Gui_Member_name() );
		Members.Add( new Gui_Member_mainMenu() );
		Members.Add( new Gui_Member_game() );
		Members.Add( new Gui_Member_parent() );
	}
	
	public override core.DataObject New() 
	{ 
		return new gui.Gui(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class GuiCommon_Member_name : reflection.ValueName
{
	public static GuiCommon_Member_name Member = new GuiCommon_Member_name 
	{ 
		Guid = new System.Guid("babd8503-cb53-417a-9de6-406313193f2c") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		gui.GuiCommon This = ThisUnityped as gui.GuiCommon;
		if ( This == null )
			return false;
		
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;

		This.name = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		gui.GuiCommon This = ThisUnityped as gui.GuiCommon;
		if ( This == null )
			return false;

		string_Boxed dataObject = new string_Boxed();
		dataObject.value = This.name;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteBytes( System.Text.Encoding.ASCII.GetBytes( dataObject.value ) );
		
		return true;
	}	
};

public class GuiCommon_Member_files : reflection.Collection
{
	public static GuiCommon_Member_files Member = new GuiCommon_Member_files 
	{ 
		Guid = new System.Guid("b0e3237a-56fc-4190-aa49-7b89fa9bc31b") 
	};
	
	public override bool GetCollectionObject( core.DataObject ThisUnityped, ref core.DataObject collectionUnityped )
	{
		gui.GuiCommon This = ThisUnityped as gui.GuiCommon;
		if ( This == null )
			return false;
			
		collectionUnityped = This.files;
		return true;
	}
};

public class GuiCommon_Member_parent : reflection.ParentReference
{
	public static GuiCommon_Member_parent Member = new GuiCommon_Member_parent 
	{ 
		Guid = new System.Guid("a1543822-a955-4f35-96f4-956e713fbded") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		gui.GuiCommon This = ThisUnityped as gui.GuiCommon;
		if ( This == null )
			return false;
			
		gui.Gui dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as gui.Gui;
			if ( dataObject == null )
				return false;
		}		
		This.parent = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		gui.GuiCommon This = ThisUnityped as gui.GuiCommon;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.parent;
		return true;	
	}
};

public class GuiCommon_Reflection : reflection.FolderStorageClass
{
	public static GuiCommon_Reflection MetadataClass = new GuiCommon_Reflection 
	{ 
		  Guid = new System.Guid("89151a41-bdf2-4047-ad2b-1cb5ca1da1f2")
	};
	
	public GuiCommon_Reflection()
	{
		Members.Add( new GuiCommon_Member_name() );
		Members.Add( new GuiCommon_Member_files() );
		Members.Add( new GuiCommon_Member_parent() );
	}
	
	public override core.DataObject New() 
	{ 
		return new gui.GuiCommon(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class GuiMainMenu_Reflection : reflection.FolderStorageClass
{
	public static GuiMainMenu_Reflection MetadataClass = new GuiMainMenu_Reflection 
	{ 
		  Guid = new System.Guid("97e2754c-a946-42d5-b961-517108e29fad")
		, BaseClass = GuiCommon_Reflection.MetadataClass
	};
	
	public GuiMainMenu_Reflection()
	{
	}
	
	public override core.DataObject New() 
	{ 
		return new gui.GuiMainMenu(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class GuiGame_Reflection : reflection.FolderStorageClass
{
	public static GuiGame_Reflection MetadataClass = new GuiGame_Reflection 
	{ 
		  Guid = new System.Guid("ad753820-7e98-4910-a473-03cf514b4276")
		, BaseClass = GuiCommon_Reflection.MetadataClass
	};
	
	public GuiGame_Reflection()
	{
	}
	
	public override core.DataObject New() 
	{ 
		return new gui.GuiGame(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class GuiFile_Member_mainWindow : reflection.FileStorage
{
	public static GuiFile_Member_mainWindow Member = new GuiFile_Member_mainWindow 
	{ 
		Guid = new System.Guid("5625d372-0afb-4361-8566-efe830187a8d") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		gui.GuiFile This = ThisUnityped as gui.GuiFile;
		if ( This == null )
			return false;
			
		gui.Window dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as gui.Window;
			if ( dataObject == null )
				return false;
		}		
		This.mainWindow = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		gui.GuiFile This = ThisUnityped as gui.GuiFile;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.mainWindow;
		return true;	
	}
};

public class GuiFile_Member_parent : reflection.ParentReference
{
	public static GuiFile_Member_parent Member = new GuiFile_Member_parent 
	{ 
		Guid = new System.Guid("f8d10f70-4b40-46d9-b44b-c9818ced46fa") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		gui.GuiFile This = ThisUnityped as gui.GuiFile;
		if ( This == null )
			return false;
			
		gui.GuiCommon dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as gui.GuiCommon;
			if ( dataObject == null )
				return false;
		}		
		This.parent = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		gui.GuiFile This = ThisUnityped as gui.GuiFile;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.parent;
		return true;	
	}
};

public class GuiFile_Member_name : reflection.ValueName
{
	public static GuiFile_Member_name Member = new GuiFile_Member_name 
	{ 
		Guid = new System.Guid("e078e0df-a369-4162-b00c-cb283743209a") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		gui.GuiFile This = ThisUnityped as gui.GuiFile;
		if ( This == null )
			return false;
		
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;

		This.name = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		gui.GuiFile This = ThisUnityped as gui.GuiFile;
		if ( This == null )
			return false;

		string_Boxed dataObject = new string_Boxed();
		dataObject.value = This.name;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteBytes( System.Text.Encoding.ASCII.GetBytes( dataObject.value ) );
		
		return true;
	}	
};

public class GuiFile_Reflection : reflection.FileClass
{
	public static GuiFile_Reflection MetadataClass = new GuiFile_Reflection 
	{ 
		  Guid = new System.Guid("37a5ca1e-d8ce-4dbd-9f69-48af50cf494a")
	};
	
	public GuiFile_Reflection()
	{
		Members.Add( new GuiFile_Member_mainWindow() );
		Members.Add( new GuiFile_Member_parent() );
		Members.Add( new GuiFile_Member_name() );
	}
	
	public override core.DataObject New() 
	{ 
		return new gui.GuiFile(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class GuiFilesCollection_Reflection : reflection.CollectionClass
{
	public static GuiFilesCollection_Reflection MetadataClass = new GuiFilesCollection_Reflection 
	{ 
		  Guid = new System.Guid("fb8ededb-c8ae-4208-a6cf-4d31c5508cb6")
	};
	
	public GuiFilesCollection_Reflection()
	{
	}
	
	public override core.DataObject New() 
	{ 
		return new gui.GuiFilesCollection(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


} /* namespace gui */ 
