
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

namespace level { 

public class Levels_Member_name : reflection.ValueName
{
	public static Levels_Member_name Member = new Levels_Member_name 
	{ 
		Guid = new System.Guid("2fccc80d-24cd-4f58-9f2c-19a1dee87f9b") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		level.Levels This = ThisUnityped as level.Levels;
		if ( This == null )
			return false;
		
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;

		This.name = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		level.Levels This = ThisUnityped as level.Levels;
		if ( This == null )
			return false;

		string_Boxed dataObject = new string_Boxed();
		dataObject.value = This.name;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteBytes( System.Text.Encoding.ASCII.GetBytes( dataObject.value ) );
		
		return true;
	}	
};

public class Levels_Member_folders : reflection.Collection
{
	public static Levels_Member_folders Member = new Levels_Member_folders 
	{ 
		Guid = new System.Guid("6d4f2370-78c6-4101-9cc7-0f28e4a18045") 
	};
	
	public override bool GetCollectionObject( core.DataObject ThisUnityped, ref core.DataObject collectionUnityped )
	{
		level.Levels This = ThisUnityped as level.Levels;
		if ( This == null )
			return false;
			
		collectionUnityped = This.folders;
		return true;
	}
};

public class Levels_Member_parent : reflection.ParentReference
{
	public static Levels_Member_parent Member = new Levels_Member_parent 
	{ 
		Guid = new System.Guid("26cd9e14-4865-41b4-b074-a63cb275af8d") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		level.Levels This = ThisUnityped as level.Levels;
		if ( This == null )
			return false;
			
		game.Game dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as game.Game;
			if ( dataObject == null )
				return false;
		}		
		This.parent = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		level.Levels This = ThisUnityped as level.Levels;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.parent;
		return true;	
	}
};

public class Levels_Reflection : reflection.FolderClass
{
	public static Levels_Reflection MetadataClass = new Levels_Reflection 
	{ 
		  Guid = new System.Guid("daaf8113-6b58-48a3-a19e-94b9e6da3a74")
	};
	
	public Levels_Reflection()
	{
		Members.Add( new Levels_Member_name() );
		Members.Add( new Levels_Member_folders() );
		Members.Add( new Levels_Member_parent() );
	}
	
	public override core.DataObject New() 
	{ 
		return new level.Levels(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class LevelFolder_Member_name : reflection.ValueName
{
	public static LevelFolder_Member_name Member = new LevelFolder_Member_name 
	{ 
		Guid = new System.Guid("52f0b117-c9c7-4825-967e-f12bcd128c45") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		level.LevelFolder This = ThisUnityped as level.LevelFolder;
		if ( This == null )
			return false;
		
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;

		This.name = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		level.LevelFolder This = ThisUnityped as level.LevelFolder;
		if ( This == null )
			return false;

		string_Boxed dataObject = new string_Boxed();
		dataObject.value = This.name;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteBytes( System.Text.Encoding.ASCII.GetBytes( dataObject.value ) );
		
		return true;
	}	
};

public class LevelFolder_Member_parent : reflection.ParentReference
{
	public static LevelFolder_Member_parent Member = new LevelFolder_Member_parent 
	{ 
		Guid = new System.Guid("58361e6e-810c-4720-93fa-1ecc7307ea91") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		level.LevelFolder This = ThisUnityped as level.LevelFolder;
		if ( This == null )
			return false;
			
		level.Levels dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as level.Levels;
			if ( dataObject == null )
				return false;
		}		
		This.parent = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		level.LevelFolder This = ThisUnityped as level.LevelFolder;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.parent;
		return true;	
	}
};

public class LevelFolder_Member_dependencies : reflection.Collection
{
	public static LevelFolder_Member_dependencies Member = new LevelFolder_Member_dependencies 
	{ 
		Guid = new System.Guid("2a19daa4-3fe7-4b9a-acca-22a584477e7f") 
	};
	
	public override bool GetCollectionObject( core.DataObject ThisUnityped, ref core.DataObject collectionUnityped )
	{
		level.LevelFolder This = ThisUnityped as level.LevelFolder;
		if ( This == null )
			return false;
			
		collectionUnityped = This.dependencies;
		return true;
	}
};

public class LevelFolder_Member_blocks : reflection.Collection
{
	public static LevelFolder_Member_blocks Member = new LevelFolder_Member_blocks 
	{ 
		Guid = new System.Guid("b83ac6fc-4ebe-4bcf-8ede-c3ce3e2f67a4") 
	};
	
	public override bool GetCollectionObject( core.DataObject ThisUnityped, ref core.DataObject collectionUnityped )
	{
		level.LevelFolder This = ThisUnityped as level.LevelFolder;
		if ( This == null )
			return false;
			
		collectionUnityped = This.blocks;
		return true;
	}
};

public class LevelFolder_Reflection : reflection.FolderStorageClass
{
	public static LevelFolder_Reflection MetadataClass = new LevelFolder_Reflection 
	{ 
		  Guid = new System.Guid("65461cf1-2c85-4ab0-9ed8-7a951902236f")
	};
	
	public LevelFolder_Reflection()
	{
		Members.Add( new LevelFolder_Member_name() );
		Members.Add( new LevelFolder_Member_parent() );
		Members.Add( new LevelFolder_Member_dependencies() );
		Members.Add( new LevelFolder_Member_blocks() );
	}
	
	public override core.DataObject New() 
	{ 
		return new level.LevelFolder(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class LevelFoldersCollection_Reflection : reflection.CollectionClass
{
	public static LevelFoldersCollection_Reflection MetadataClass = new LevelFoldersCollection_Reflection 
	{ 
		  Guid = new System.Guid("e7cb809a-fa8f-4b52-9680-b18d03cb1a5e")
	};
	
	public LevelFoldersCollection_Reflection()
	{
	}
	
	public override core.DataObject New() 
	{ 
		return new level.LevelFoldersCollection(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class LevelBlock_Member_name : reflection.ValueName
{
	public static LevelBlock_Member_name Member = new LevelBlock_Member_name 
	{ 
		Guid = new System.Guid("8b004694-164b-4678-b912-2ca3b24fe8b7") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		level.LevelBlock This = ThisUnityped as level.LevelBlock;
		if ( This == null )
			return false;
		
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;

		This.name = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		level.LevelBlock This = ThisUnityped as level.LevelBlock;
		if ( This == null )
			return false;

		string_Boxed dataObject = new string_Boxed();
		dataObject.value = This.name;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteBytes( System.Text.Encoding.ASCII.GetBytes( dataObject.value ) );
		
		return true;
	}	
};

public class LevelBlock_Member_parent : reflection.ParentReference
{
	public static LevelBlock_Member_parent Member = new LevelBlock_Member_parent 
	{ 
		Guid = new System.Guid("8c862cca-79fa-436d-a320-66ee7e3bc936") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		level.LevelBlock This = ThisUnityped as level.LevelBlock;
		if ( This == null )
			return false;
			
		level.LevelFolder dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as level.LevelFolder;
			if ( dataObject == null )
				return false;
		}		
		This.parent = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		level.LevelBlock This = ThisUnityped as level.LevelBlock;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.parent;
		return true;	
	}
};

public class LevelBlock_Member_files : reflection.Collection
{
	public static LevelBlock_Member_files Member = new LevelBlock_Member_files 
	{ 
		Guid = new System.Guid("084f1b7f-89f2-4f03-8dff-14fec74b1fc9") 
	};
	
	public override bool GetCollectionObject( core.DataObject ThisUnityped, ref core.DataObject collectionUnityped )
	{
		level.LevelBlock This = ThisUnityped as level.LevelBlock;
		if ( This == null )
			return false;
			
		collectionUnityped = This.files;
		return true;
	}
};

public class LevelBlock_Reflection : reflection.FolderClass
{
	public static LevelBlock_Reflection MetadataClass = new LevelBlock_Reflection 
	{ 
		  Guid = new System.Guid("77924162-cb05-4f79-969e-6854a43ae1c8")
	};
	
	public LevelBlock_Reflection()
	{
		Members.Add( new LevelBlock_Member_name() );
		Members.Add( new LevelBlock_Member_parent() );
		Members.Add( new LevelBlock_Member_files() );
	}
	
	public override core.DataObject New() 
	{ 
		return new level.LevelBlock(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class LevelBlocksCollection_Reflection : reflection.CollectionClass
{
	public static LevelBlocksCollection_Reflection MetadataClass = new LevelBlocksCollection_Reflection 
	{ 
		  Guid = new System.Guid("4c2def93-2fcb-4c8f-851c-88aa2c98cfd4")
	};
	
	public LevelBlocksCollection_Reflection()
	{
	}
	
	public override core.DataObject New() 
	{ 
		return new level.LevelBlocksCollection(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class LevelFile_Member_parent : reflection.ParentReference
{
	public static LevelFile_Member_parent Member = new LevelFile_Member_parent 
	{ 
		Guid = new System.Guid("33d91469-0caa-4708-a19c-d647c0b41ff0") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		level.LevelFile This = ThisUnityped as level.LevelFile;
		if ( This == null )
			return false;
			
		level.LevelBlock dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as level.LevelBlock;
			if ( dataObject == null )
				return false;
		}		
		This.parent = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		level.LevelFile This = ThisUnityped as level.LevelFile;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.parent;
		return true;	
	}
};

public class LevelFile_Member_scene : reflection.FileStorage
{
	public static LevelFile_Member_scene Member = new LevelFile_Member_scene 
	{ 
		Guid = new System.Guid("e502c1ab-993e-4d66-9366-a4eca621be55") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		level.LevelFile This = ThisUnityped as level.LevelFile;
		if ( This == null )
			return false;
			
		scene.Scene dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as scene.Scene;
			if ( dataObject == null )
				return false;
		}		
		This.scene = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		level.LevelFile This = ThisUnityped as level.LevelFile;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.scene;
		return true;	
	}
};

public class LevelFile_Member_name : reflection.ValueName
{
	public static LevelFile_Member_name Member = new LevelFile_Member_name 
	{ 
		Guid = new System.Guid("784e344b-a1c4-4ce8-8faf-f40e1c3562a2") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		level.LevelFile This = ThisUnityped as level.LevelFile;
		if ( This == null )
			return false;
		
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;

		This.name = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		level.LevelFile This = ThisUnityped as level.LevelFile;
		if ( This == null )
			return false;

		string_Boxed dataObject = new string_Boxed();
		dataObject.value = This.name;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteBytes( System.Text.Encoding.ASCII.GetBytes( dataObject.value ) );
		
		return true;
	}	
};

public class LevelFile_Reflection : reflection.FileClass
{
	public static LevelFile_Reflection MetadataClass = new LevelFile_Reflection 
	{ 
		  Guid = new System.Guid("5a4f1500-59c4-430c-89ac-fa1fdfa88e46")
	};
	
	public LevelFile_Reflection()
	{
		Members.Add( new LevelFile_Member_parent() );
		Members.Add( new LevelFile_Member_scene() );
		Members.Add( new LevelFile_Member_name() );
	}
	
	public override core.DataObject New() 
	{ 
		return new level.LevelFile(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class LevelFilesCollection_Reflection : reflection.CollectionClass
{
	public static LevelFilesCollection_Reflection MetadataClass = new LevelFilesCollection_Reflection 
	{ 
		  Guid = new System.Guid("17a293e5-b01a-4095-b5f7-17d74a0c9b8b")
	};
	
	public LevelFilesCollection_Reflection()
	{
	}
	
	public override core.DataObject New() 
	{ 
		return new level.LevelFilesCollection(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class Dependency_Member_LevelFolder : reflection.Reference
{
	public static Dependency_Member_LevelFolder Member = new Dependency_Member_LevelFolder 
	{ 
		Guid = new System.Guid("cd7d237b-6fe5-4deb-8da2-415994aeec66") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		level.Dependency This = ThisUnityped as level.Dependency;
		if ( This == null )
			return false;
			
		level.LevelFolder dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as level.LevelFolder;
			if ( dataObject == null )
				return false;
		}		
		This.LevelFolder = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		level.Dependency This = ThisUnityped as level.Dependency;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.LevelFolder;
		return true;	
	}
};

public class Dependency_Reflection : reflection.MetadataClass
{
	public static Dependency_Reflection MetadataClass = new Dependency_Reflection 
	{ 
		  Guid = new System.Guid("2956cd4f-619d-4fc7-bfc4-84722fd742d5")
	};
	
	public Dependency_Reflection()
	{
		Members.Add( new Dependency_Member_LevelFolder() );
	}
	
	public override core.DataObject New() 
	{ 
		return new level.Dependency(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class Dependencies_Reflection : reflection.CollectionClass
{
	public static Dependencies_Reflection MetadataClass = new Dependencies_Reflection 
	{ 
		  Guid = new System.Guid("c5c17415-7309-489b-ae23-61f4ef69c532")
	};
	
	public Dependencies_Reflection()
	{
	}
	
	public override core.DataObject New() 
	{ 
		return new level.Dependencies(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


} /* namespace level */ 
