
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

using System;
using System.Collections.Generic;

namespace game { 

	public static class Game_ByteStream
	{
		public static void ObjectToByteStream( core.ByteStreamWriter stream, game.Game dataObject ) 
		{ 
			game.Globals_ByteStream.ObjectToByteStream( stream, dataObject.globals );
			gui.Gui_ByteStream.ObjectToByteStream( stream, dataObject.gui );
			level.Levels_ByteStream.ObjectToByteStream( stream, dataObject.levels );
		}		
	}

} /* namespace game */ 
