
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

namespace game { 

public class Game_Member_globals : reflection.Value
{
	public static Game_Member_globals Member = new Game_Member_globals 
	{ 
		Guid = new System.Guid("17cf6cc9-44c8-4f8f-ac47-1b6093007641") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		game.Game This = ThisUnityped as game.Game;
		if ( This == null )
			return false;
			
		game.Globals dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as game.Globals;
			if ( dataObject == null )
				return false;
		}		
		This.globals = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		game.Game This = ThisUnityped as game.Game;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.globals;
		return true;	
	}
};

public class Game_Member_gui : reflection.Value
{
	public static Game_Member_gui Member = new Game_Member_gui 
	{ 
		Guid = new System.Guid("76d80037-df45-4a70-97e5-d03b47c1b26f") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		game.Game This = ThisUnityped as game.Game;
		if ( This == null )
			return false;
			
		gui.Gui dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as gui.Gui;
			if ( dataObject == null )
				return false;
		}		
		This.gui = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		game.Game This = ThisUnityped as game.Game;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.gui;
		return true;	
	}
};

public class Game_Member_levels : reflection.Value
{
	public static Game_Member_levels Member = new Game_Member_levels 
	{ 
		Guid = new System.Guid("200e773c-0740-4dc1-ad0b-1d41d669f045") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		game.Game This = ThisUnityped as game.Game;
		if ( This == null )
			return false;
			
		level.Levels dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as level.Levels;
			if ( dataObject == null )
				return false;
		}		
		This.levels = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		game.Game This = ThisUnityped as game.Game;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.levels;
		return true;	
	}
};

public class Game_Member_SetObjectValue_Server : reflection.FunctionUser
{
	public static Game_Member_SetObjectValue_Server Member = new Game_Member_SetObjectValue_Server 
	{ 
		Guid = new System.Guid("3491d868-eb38-4bdb-8e24-404a06714f29") 
	};
	
};

public class Game_Member_SetObjectReference_Server : reflection.FunctionUser
{
	public static Game_Member_SetObjectReference_Server Member = new Game_Member_SetObjectReference_Server 
	{ 
		Guid = new System.Guid("0fbf300f-6504-4d20-841a-64d70eea4796") 
	};
	
};

public class Game_Member_SetObjectParentReference_Server : reflection.FunctionUser
{
	public static Game_Member_SetObjectParentReference_Server Member = new Game_Member_SetObjectParentReference_Server 
	{ 
		Guid = new System.Guid("d1c5f8b9-a077-40d2-8b14-37a2d6887af0") 
	};
	
};

public class Game_Member_SetObjectFileStorage_Server : reflection.FunctionUser
{
	public static Game_Member_SetObjectFileStorage_Server Member = new Game_Member_SetObjectFileStorage_Server 
	{ 
		Guid = new System.Guid("7de35da6-b5c6-4c59-898d-674e50be4a93") 
	};
	
};

public class Game_Member_NewObject_Server : reflection.FunctionUser
{
	public static Game_Member_NewObject_Server Member = new Game_Member_NewObject_Server 
	{ 
		Guid = new System.Guid("f12e94f1-f3e1-4cc1-9fda-1fb7eaed0316") 
	};
	
};

public class Game_Member_DeleteObject_Server : reflection.FunctionUser
{
	public static Game_Member_DeleteObject_Server Member = new Game_Member_DeleteObject_Server 
	{ 
		Guid = new System.Guid("5f86a605-9657-4ed8-a312-3e67229df7e3") 
	};
	
};

public class Game_Reflection : reflection.ProjectClass
{
	public static Game_Reflection MetadataClass = new Game_Reflection 
	{ 
		  Guid = new System.Guid("56e8a41d-bf20-475f-aa07-0a512975f527")
	};
	
	public Game_Reflection()
	{
		Members.Add( new Game_Member_globals() );
		Members.Add( new Game_Member_gui() );
		Members.Add( new Game_Member_levels() );
		Members.Add( new Game_Member_SetObjectValue_Server() );
		Members.Add( new Game_Member_SetObjectReference_Server() );
		Members.Add( new Game_Member_SetObjectParentReference_Server() );
		Members.Add( new Game_Member_SetObjectFileStorage_Server() );
		Members.Add( new Game_Member_NewObject_Server() );
		Members.Add( new Game_Member_DeleteObject_Server() );
	}
	
	public override core.DataObject New() 
	{ 
		return new game.Game(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


} /* namespace game */ 
