
// AUTOGENERATED FILE. MODIFY IT AT YOUR OWN RISK.

namespace scene { 

public class SceneObject_Member_parent : reflection.ParentReference
{
	public static SceneObject_Member_parent Member = new SceneObject_Member_parent 
	{ 
		Guid = new System.Guid("ab60af94-9cf8-4825-a1c9-77c35fe7b49a") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;
			
		scene.Scene dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as scene.Scene;
			if ( dataObject == null )
				return false;
		}		
		This.parent = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.parent;
		return true;	
	}
};

public class SceneObject_Member_position : reflection.Value
{
	public static SceneObject_Member_position Member = new SceneObject_Member_position 
	{ 
		Guid = new System.Guid("fae85196-efcd-4004-a660-afbbc4ccb7d9") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;
		
		Vec3 dataObject = dataObjectUnityped as Vec3;		
		if ( dataObject == null )
			return false;

		This.position = dataObject;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;

		dataObjectUnityped = This.position;
		return true;
	}
};

public class SceneObject_Member_scale : reflection.Value
{
	public static SceneObject_Member_scale Member = new SceneObject_Member_scale 
	{ 
		Guid = new System.Guid("1a72eee7-8cae-4d96-895c-5004ca2539b1") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;
		
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;

		This.scale = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;

		float_Boxed dataObject = new float_Boxed();
		dataObject.value = This.scale;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteFloat32( dataObject.value );
		
		return true;
	}	
};

public class SceneObject_Member_color : reflection.Value
{
	public static SceneObject_Member_color Member = new SceneObject_Member_color 
	{ 
		Guid = new System.Guid("ef540747-1aee-44f5-b67f-83b164495fe9") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;
		
		Color dataObject = dataObjectUnityped as Color;		
		if ( dataObject == null )
			return false;

		This.color = dataObject;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;

		dataObjectUnityped = This.color;
		return true;
	}
};

public class SceneObject_Member_lod : reflection.Value
{
	public static SceneObject_Member_lod Member = new SceneObject_Member_lod 
	{ 
		Guid = new System.Guid("4d99ebcb-27de-4835-8317-be504f3959f7") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;
		
		int_Boxed dataObject = dataObjectUnityped as int_Boxed;		
		if ( dataObject == null )
			return false;

		This.lod = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;

		int_Boxed dataObject = new int_Boxed();
		dataObject.value = This.lod;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		int_Boxed dataObject = dataObjectUnityped as int_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteInt32( dataObject.value );
		
		return true;
	}	
};

public class SceneObject_Member_visible : reflection.Value
{
	public static SceneObject_Member_visible Member = new SceneObject_Member_visible 
	{ 
		Guid = new System.Guid("22df5858-12d4-4b51-86be-061df2d04dcc") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;
		
		bool_Boxed dataObject = dataObjectUnityped as bool_Boxed;		
		if ( dataObject == null )
			return false;

		This.visible = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;

		bool_Boxed dataObject = new bool_Boxed();
		dataObject.value = This.visible;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		bool_Boxed dataObject = dataObjectUnityped as bool_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteUint8( dataObject.value ? (byte)1 : (byte)0 );
		
		return true;
	}	
};

public class SceneObject_Member_next : reflection.Reference
{
	public static SceneObject_Member_next Member = new SceneObject_Member_next 
	{ 
		Guid = new System.Guid("386ddb5c-8c5b-4724-ab45-620990bf5cca") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;
			
		scene.SceneObject dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as scene.SceneObject;
			if ( dataObject == null )
				return false;
		}		
		This.next = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.next;
		return true;	
	}
};

public class SceneObject_Member_isSoundEnabled : reflection.Value
{
	public static SceneObject_Member_isSoundEnabled Member = new SceneObject_Member_isSoundEnabled 
	{ 
		Guid = new System.Guid("82d53064-cdaf-4689-92be-76bd5ce1baf8") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;
		
		bool_Boxed dataObject = dataObjectUnityped as bool_Boxed;		
		if ( dataObject == null )
			return false;

		This.isSoundEnabled = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;

		bool_Boxed dataObject = new bool_Boxed();
		dataObject.value = This.isSoundEnabled;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		bool_Boxed dataObject = dataObjectUnityped as bool_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteUint8( dataObject.value ? (byte)1 : (byte)0 );
		
		return true;
	}	
};

public class SceneObject_Member_isSfxEnabled : reflection.Value
{
	public static SceneObject_Member_isSfxEnabled Member = new SceneObject_Member_isSfxEnabled 
	{ 
		Guid = new System.Guid("3fd380ef-b117-407a-b784-67101f443878") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;
		
		bool_Boxed dataObject = dataObjectUnityped as bool_Boxed;		
		if ( dataObject == null )
			return false;

		This.isSfxEnabled = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneObject This = ThisUnityped as scene.SceneObject;
		if ( This == null )
			return false;

		bool_Boxed dataObject = new bool_Boxed();
		dataObject.value = This.isSfxEnabled;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		bool_Boxed dataObject = dataObjectUnityped as bool_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteUint8( dataObject.value ? (byte)1 : (byte)0 );
		
		return true;
	}	
};

public class SceneObject_Member_TestFunction : reflection.FunctionUser
{
	public static SceneObject_Member_TestFunction Member = new SceneObject_Member_TestFunction 
	{ 
		Guid = new System.Guid("c4b461bf-af49-4925-874f-68827e86e992") 
	};
	
};

public class SceneObject_Member_TestLua : reflection.FunctionUser
{
	public static SceneObject_Member_TestLua Member = new SceneObject_Member_TestLua 
	{ 
		Guid = new System.Guid("6d1bdbcb-6541-4485-85ba-e531c5fd9a4c") 
	};
	
};

public class SceneObject_Member_TestLuaCC : reflection.FunctionLuaCallCC
{
	public static SceneObject_Member_TestLuaCC Member = new SceneObject_Member_TestLuaCC 
	{ 
		Guid = new System.Guid("d02c0264-fb6c-42a1-9fef-8924f71f122c") 
	};
	
};

public class SceneObject_Member_LuaConstructor : reflection.FunctionLua
{
	public static SceneObject_Member_LuaConstructor Member = new SceneObject_Member_LuaConstructor 
	{ 
		Guid = new System.Guid("9bdb2933-1665-473e-bdbc-b994fdf01778") 
	};
	
};

public class SceneObject_Member_LuaDestructor : reflection.FunctionLua
{
	public static SceneObject_Member_LuaDestructor Member = new SceneObject_Member_LuaDestructor 
	{ 
		Guid = new System.Guid("f2012c64-e43e-4d48-aa03-e407ed6c20d0") 
	};
	
};

public class SceneObject_Reflection : reflection.MetadataClass
{
	public static SceneObject_Reflection MetadataClass = new SceneObject_Reflection 
	{ 
		  Guid = new System.Guid("a31ecf2f-653b-4595-8eed-c50c0d3cc116")
	};
	
	public SceneObject_Reflection()
	{
		Members.Add( new SceneObject_Member_parent() );
		Members.Add( new SceneObject_Member_position() );
		Members.Add( new SceneObject_Member_scale() );
		Members.Add( new SceneObject_Member_color() );
		Members.Add( new SceneObject_Member_lod() );
		Members.Add( new SceneObject_Member_visible() );
		Members.Add( new SceneObject_Member_next() );
		Members.Add( new SceneObject_Member_isSoundEnabled() );
		Members.Add( new SceneObject_Member_isSfxEnabled() );
		Members.Add( new SceneObject_Member_TestFunction() );
		Members.Add( new SceneObject_Member_TestLua() );
		Members.Add( new SceneObject_Member_TestLuaCC() );
		Members.Add( new SceneObject_Member_LuaConstructor() );
		Members.Add( new SceneObject_Member_LuaDestructor() );
	}
	
	public override core.DataObject New() 
	{ 
		return new scene.SceneObject(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class SceneObjectsCollection_Reflection : reflection.CollectionClass
{
	public static SceneObjectsCollection_Reflection MetadataClass = new SceneObjectsCollection_Reflection 
	{ 
		  Guid = new System.Guid("1ced8553-f8e8-428d-9a1f-8b95c40fc073")
	};
	
	public SceneObjectsCollection_Reflection()
	{
	}
	
	public override core.DataObject New() 
	{ 
		return new scene.SceneObjectsCollection(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class SceneMesh_Member_colorSnd : reflection.Value
{
	public static SceneMesh_Member_colorSnd Member = new SceneMesh_Member_colorSnd 
	{ 
		Guid = new System.Guid("58afe797-43cf-4ae2-b3d1-2d05ef2a6508") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneMesh This = ThisUnityped as scene.SceneMesh;
		if ( This == null )
			return false;
		
		Color dataObject = dataObjectUnityped as Color;		
		if ( dataObject == null )
			return false;

		This.colorSnd = dataObject;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneMesh This = ThisUnityped as scene.SceneMesh;
		if ( This == null )
			return false;

		dataObjectUnityped = This.colorSnd;
		return true;
	}
};

public class SceneMesh_Member_TestLuaDerived : reflection.FunctionUser
{
	public static SceneMesh_Member_TestLuaDerived Member = new SceneMesh_Member_TestLuaDerived 
	{ 
		Guid = new System.Guid("af593564-9f51-4793-b5c9-302a5733cd4f") 
	};
	
};

public class SceneMesh_Member_TestLuaCall : reflection.FunctionLua
{
	public static SceneMesh_Member_TestLuaCall Member = new SceneMesh_Member_TestLuaCall 
	{ 
		Guid = new System.Guid("fb2fc7e3-73da-44a4-accb-fdb6bc31e19b") 
	};
	
};

public class SceneMesh_Reflection : reflection.MetadataClass
{
	public static SceneMesh_Reflection MetadataClass = new SceneMesh_Reflection 
	{ 
		  Guid = new System.Guid("55a7a7fc-de50-4460-855c-f5a6dd785408")
		, BaseClass = SceneObject_Reflection.MetadataClass
	};
	
	public SceneMesh_Reflection()
	{
		Members.Add( new SceneMesh_Member_colorSnd() );
		Members.Add( new SceneMesh_Member_TestLuaDerived() );
		Members.Add( new SceneMesh_Member_TestLuaCall() );
	}
	
	public override core.DataObject New() 
	{ 
		return new scene.SceneMesh(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class SceneAnimMesh_Member_positionSfx : reflection.Value
{
	public static SceneAnimMesh_Member_positionSfx Member = new SceneAnimMesh_Member_positionSfx 
	{ 
		Guid = new System.Guid("b940536c-4640-414a-b89f-fa8ea1bfab65") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneAnimMesh This = ThisUnityped as scene.SceneAnimMesh;
		if ( This == null )
			return false;
		
		Vec3 dataObject = dataObjectUnityped as Vec3;		
		if ( dataObject == null )
			return false;

		This.positionSfx = dataObject;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneAnimMesh This = ThisUnityped as scene.SceneAnimMesh;
		if ( This == null )
			return false;

		dataObjectUnityped = This.positionSfx;
		return true;
	}
};

public class SceneAnimMesh_Reflection : reflection.MetadataClass
{
	public static SceneAnimMesh_Reflection MetadataClass = new SceneAnimMesh_Reflection 
	{ 
		  Guid = new System.Guid("45cb2111-a7ed-430c-9ae2-73653daad168")
		, BaseClass = SceneMesh_Reflection.MetadataClass
	};
	
	public SceneAnimMesh_Reflection()
	{
		Members.Add( new SceneAnimMesh_Member_positionSfx() );
	}
	
	public override core.DataObject New() 
	{ 
		return new scene.SceneAnimMesh(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class SceneZoneTrigger_Member_name : reflection.ValueName
{
	public static SceneZoneTrigger_Member_name Member = new SceneZoneTrigger_Member_name 
	{ 
		Guid = new System.Guid("14e3e158-5114-45c1-b590-ba801322dbb9") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneZoneTrigger This = ThisUnityped as scene.SceneZoneTrigger;
		if ( This == null )
			return false;
		
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;

		This.name = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneZoneTrigger This = ThisUnityped as scene.SceneZoneTrigger;
		if ( This == null )
			return false;

		string_Boxed dataObject = new string_Boxed();
		dataObject.value = This.name;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		string_Boxed dataObject = dataObjectUnityped as string_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteBytes( System.Text.Encoding.ASCII.GetBytes( dataObject.value ) );
		
		return true;
	}	
};

public class SceneZoneTrigger_Member_triggerType : reflection.Value
{
	public static SceneZoneTrigger_Member_triggerType Member = new SceneZoneTrigger_Member_triggerType 
	{ 
		Guid = new System.Guid("bf587132-4030-4b95-9206-68bea3467071") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneZoneTrigger This = ThisUnityped as scene.SceneZoneTrigger;
		if ( This == null )
			return false;
		
		scene.TriggerType_Boxed dataObject = dataObjectUnityped as scene.TriggerType_Boxed;		
		if ( dataObject == null )
			return false;

		This.triggerType = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneZoneTrigger This = ThisUnityped as scene.SceneZoneTrigger;
		if ( This == null )
			return false;

		scene.TriggerType_Boxed dataObject = new scene.TriggerType_Boxed();
		dataObject.value = This.triggerType;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		scene.TriggerType_Boxed dataObject = dataObjectUnityped as scene.TriggerType_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteInt32( (int)dataObject.value );
		
		return true;
	}	
};

public class SceneZoneTrigger_Member_ctrl : reflection.Value
{
	public static SceneZoneTrigger_Member_ctrl Member = new SceneZoneTrigger_Member_ctrl 
	{ 
		Guid = new System.Guid("fed64754-90c4-40c8-a900-c90f6989234b") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.SceneZoneTrigger This = ThisUnityped as scene.SceneZoneTrigger;
		if ( This == null )
			return false;
			
		scene.Controller dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as scene.Controller;
			if ( dataObject == null )
				return false;
		}		
		This.ctrl = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.SceneZoneTrigger This = ThisUnityped as scene.SceneZoneTrigger;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.ctrl;
		return true;	
	}
};

public class SceneZoneTrigger_Reflection : reflection.MetadataClass
{
	public static SceneZoneTrigger_Reflection MetadataClass = new SceneZoneTrigger_Reflection 
	{ 
		  Guid = new System.Guid("76ca5dae-e0ec-486b-ad22-48ac05249b6d")
		, BaseClass = SceneObject_Reflection.MetadataClass
	};
	
	public SceneZoneTrigger_Reflection()
	{
		Members.Add( new SceneZoneTrigger_Member_name() );
		Members.Add( new SceneZoneTrigger_Member_triggerType() );
		Members.Add( new SceneZoneTrigger_Member_ctrl() );
	}
	
	public override core.DataObject New() 
	{ 
		return new scene.SceneZoneTrigger(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class Scene_Member_mainObject : reflection.Value
{
	public static Scene_Member_mainObject Member = new Scene_Member_mainObject 
	{ 
		Guid = new System.Guid("e62c2b4b-84f5-419b-9d6a-1f8935aae81d") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.Scene This = ThisUnityped as scene.Scene;
		if ( This == null )
			return false;
			
		scene.SceneObject dataObject = null;
		if ( dataObjectUnityped != null )
		{
			dataObject = dataObjectUnityped as scene.SceneObject;
			if ( dataObject == null )
				return false;
		}		
		This.mainObject = dataObject;
		return true;	
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.Scene This = ThisUnityped as scene.Scene;
		if ( This == null )
			return false;
			
		dataObjectUnityped = This.mainObject;
		return true;	
	}
};

public class Scene_Member_objects : reflection.Collection
{
	public static Scene_Member_objects Member = new Scene_Member_objects 
	{ 
		Guid = new System.Guid("bb1154d6-63fa-483e-a6fa-14f7549549f5") 
	};
	
	public override bool GetCollectionObject( core.DataObject ThisUnityped, ref core.DataObject collectionUnityped )
	{
		scene.Scene This = ThisUnityped as scene.Scene;
		if ( This == null )
			return false;
			
		collectionUnityped = This.objects;
		return true;
	}
};

public class Scene_Reflection : reflection.MetadataClass
{
	public static Scene_Reflection MetadataClass = new Scene_Reflection 
	{ 
		  Guid = new System.Guid("20df3bc1-db3d-443e-9cff-b4f14426f1be")
	};
	
	public Scene_Reflection()
	{
		Members.Add( new Scene_Member_mainObject() );
		Members.Add( new Scene_Member_objects() );
	}
	
	public override core.DataObject New() 
	{ 
		return new scene.Scene(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class Controller_Member_priority : reflection.Value
{
	public static Controller_Member_priority Member = new Controller_Member_priority 
	{ 
		Guid = new System.Guid("6131e5df-025c-4f4f-878c-278c3ddb4c02") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.Controller This = ThisUnityped as scene.Controller;
		if ( This == null )
			return false;
		
		int_Boxed dataObject = dataObjectUnityped as int_Boxed;		
		if ( dataObject == null )
			return false;

		This.priority = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.Controller This = ThisUnityped as scene.Controller;
		if ( This == null )
			return false;

		int_Boxed dataObject = new int_Boxed();
		dataObject.value = This.priority;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		int_Boxed dataObject = dataObjectUnityped as int_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteInt32( dataObject.value );
		
		return true;
	}	
};

public class Controller_Reflection : reflection.AbstractClass
{
	public static Controller_Reflection MetadataClass = new Controller_Reflection 
	{ 
		  Guid = new System.Guid("34eac4c0-54b1-472f-81df-fd6e10c57087")
	};
	
	public Controller_Reflection()
	{
		Members.Add( new Controller_Member_priority() );
	}
	
	public override core.DataObject New() 
	{ 
		return null; 
	}

	public override void Delete( core.DataObject dataObject ) 
	{ 
	}
};


public class ControllerBox_Member_size : reflection.Value
{
	public static ControllerBox_Member_size Member = new ControllerBox_Member_size 
	{ 
		Guid = new System.Guid("cf046c68-1382-47a2-b6b1-ed0657db99ee") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.ControllerBox This = ThisUnityped as scene.ControllerBox;
		if ( This == null )
			return false;
		
		Vec3 dataObject = dataObjectUnityped as Vec3;		
		if ( dataObject == null )
			return false;

		This.size = dataObject;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.ControllerBox This = ThisUnityped as scene.ControllerBox;
		if ( This == null )
			return false;

		dataObjectUnityped = This.size;
		return true;
	}
};

public class ControllerBox_Reflection : reflection.MetadataClass
{
	public static ControllerBox_Reflection MetadataClass = new ControllerBox_Reflection 
	{ 
		  Guid = new System.Guid("ba5451aa-f6a3-445c-b3a2-c6955ec61c03")
		, BaseClass = Controller_Reflection.MetadataClass
	};
	
	public ControllerBox_Reflection()
	{
		Members.Add( new ControllerBox_Member_size() );
	}
	
	public override core.DataObject New() 
	{ 
		return new scene.ControllerBox(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


public class ControllerSphere_Member_radius : reflection.Value
{
	public static ControllerSphere_Member_radius Member = new ControllerSphere_Member_radius 
	{ 
		Guid = new System.Guid("4120edc6-849c-471a-ada8-42e7debb887d") 
	};
	
	public override bool SetObjectValue( core.DataObject ThisUnityped, core.DataObject dataObjectUnityped )
	{
		scene.ControllerSphere This = ThisUnityped as scene.ControllerSphere;
		if ( This == null )
			return false;
		
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;

		This.radius = dataObject.value;

		return true;
	}
	public override bool GetObjectValue( core.DataObject ThisUnityped, ref core.DataObject dataObjectUnityped )
	{
		scene.ControllerSphere This = ThisUnityped as scene.ControllerSphere;
		if ( This == null )
			return false;

		float_Boxed dataObject = new float_Boxed();
		dataObject.value = This.radius;
		
		dataObjectUnityped = dataObject;
		return true;
	}	
	public override bool GetObjectValue_ToByteStream( core.ByteStreamWriter stream, core.DataObject dataObjectUnityped ) 
	{ 
		float_Boxed dataObject = dataObjectUnityped as float_Boxed;		
		if ( dataObject == null )
			return false;
		stream.WriteFloat32( dataObject.value );
		
		return true;
	}	
};

public class ControllerSphere_Reflection : reflection.MetadataClass
{
	public static ControllerSphere_Reflection MetadataClass = new ControllerSphere_Reflection 
	{ 
		  Guid = new System.Guid("7ace5c93-0d37-41a0-bcc3-8ee7c34cacb3")
		, BaseClass = Controller_Reflection.MetadataClass
	};
	
	public ControllerSphere_Reflection()
	{
		Members.Add( new ControllerSphere_Member_radius() );
	}
	
	public override core.DataObject New() 
	{ 
		return new scene.ControllerSphere(); 
	}

	public override void Delete( core.DataObject dataObject ) 
	{
	}
};


} /* namespace scene */ 
